(function () {
  const storageKey = 'portfolio-language';
  const defaultLang = 'pt';
  const translations = {
    pt: {
      'nav.home': 'Início',
      'nav.case-studies': 'Cases',
      'nav.about': 'Sobre (CV)',
      'nav.contact': 'Contato',
      'case.back': 'Voltar',
      'page.title.home': 'Lari Toschi | Product Designer',
      'page.title.case-studies': 'Cases | Lari Toschi',
      'page.title.about': 'Sobre | Lari Toschi',
      'page.title.contact': 'Contato | Lari Toschi',
      'page.title.case-study': 'Case Study | Lari Toschi',
      'page.title.case-study-askflow': 'AskFlow Agents | Case Study',
      'page.title.case-study-retail': 'Retail Data | Case Study',
      'page.title.case-study-blip': 'Blip | Case Study',
      'page.title.case-askflow': 'AskFlow Agents • Case Completo',
      'page.title.case-retail': 'Retail Data • Case Completo',
      'page.title.case-blip': 'Blip • Case Completo',
      'hero.eyebrow': 'Designer de Produto Pl/Sr • UX Research • UI Design',
      'hero.title': 'Olá, sou a Lari! Transformo problemas complexos em experiências envolventes.',
      'hero.text': 'Combino product strategy, design de interação e insight comportamental para criar produtos intuitivos e com impacto mensurável.',
      'hero.cta.primary': 'Ver cases em destaque',
      'hero.cta.secondary': 'Vamos conversar',
      'home.about.label': 'Sobre',
      'home.about.title': 'Formada em Arquitetura com ênfase em computação pela USP, foco em produto e muita curiosidade por comportamento humano.',
      'home.about.text': 'Com mais de 5 anos de experiência, atuo próxima à estratégia de negócio, mesclando usabilidade e design, com minha maior experiência em SaaS B2B.',
      'home.featured.label': 'Cases em destaque',
      'home.featured.title': 'Trabalhos selecionados que equilibram clareza, estratégia e resultado de negócio.',
      'home.featured.link': 'Ver tudo',
      'home.carousel.label': 'Galeria de imagens',
      'home.carousel.title': 'Exemplos de design e explorações de conceito.',
      'home.carousel.slide1.title': 'Conceito de lançamento de produto',
      'home.carousel.slide1.text': 'Uma exploração visual de mensagens de lançamento e hierarquia de conteúdo em uma experiência moderna.',
      'home.carousel.slide1.cta': 'Ver mais',
      'home.carousel.slide2.title': 'Exploração de interface',
      'home.carousel.slide2.text': 'Um conceito de interface que destaca clareza, espaçamento e hierarquia de conteúdo entre telas.',
      'home.carousel.slide2.cta': 'Ver mais',
      'home.carousel.slide3.title': 'Prévia de dashboard',
      'home.carousel.slide3.text': 'Um conceito de dashboard leve com overlay sutil e um botão discreto para ver mais.',
      'home.carousel.slide3.cta': 'Ver mais',
      'home.featured.card.askflow.pill': 'AskFlow Agents',
      'home.featured.card.askflow.title': 'Simplificando a ativação de IA para impulsionar o crescimento do negócio',
      'home.featured.card.askflow.desc': 'Redesenhei um editor conversacional complexo em uma biblioteca de templates leve e aumentei as ativações mensais em 40%.',
      'home.featured.card.askflow.meta1': '+40% de ativações mensais',
      'home.featured.card.askflow.meta2': 'Configuração em menos de 1 minuto',
      'home.featured.card.askflow.meta3': 'Menor carga de suporte',
      'home.featured.card.blip.pill': 'Dashboard de Cobrança',
      'home.featured.card.blip.title': 'Consolidando métricas de uso em uma experiência SaaS mais clara',
      'home.featured.card.blip.desc': 'Transformei dados operacionais fragmentados em uma interface mais clara que reduziu confusão e custos de suporte.',
      'home.featured.card.retail.pill': 'Analytics de Varejo',
      'home.featured.card.retail.title': 'Triangulação de dados para uma estratégia de CRM mais conversora',
      'home.featured.card.retail.desc': 'Estruturei um dashboard de varejo para unificar sinais de checkout e verificações de qualidade em uma superfície de decisão mais clara.',
      'home.contact.label': 'Vamos conversar',
      'home.contact.title': 'Aberta para freelancing e disposta a conversar sobre oportunidades em product e UX design.',
      'home.contact.cta': 'Entre em contato',
      'about.intro.label': 'Sobre',
      'about.intro.title': 'Designer de produto com visão de sistemas e abordagem centrada no usuário.',
      'about.intro.text': 'Formada em Arquitetura pela USP com foco em computação. Com mais de 5 anos de experiência em UX e produto, conecto estratégia, design e implementação para construir produtos intuitivos, simples e escaláveis.',
      'about.profile.title': 'Atualmente baseada em',
      'about.profile.location': 'Taubaté, SP',
      'about.profile.description': 'Vive com o marido e seus 4 gatos. Ama livros de psicologia, café chique e design bem feito.',
      'about.experience.title': 'Experiência',
      'about.experience.job1.title': 'Designer de Produto Sênior',
      'about.experience.job1.company': 'Omnichat',
      'about.experience.job1.period': 'Mai 2026 – Atual',
      'about.experience.job1.desc': 'Desenhando a experiência end-to-end da Whizz, uma plataforma de agentes de IA para e-commerce, tornando fluxos complexos de automação e integrações via API acessíveis a usuários não técnicos.',
      'about.experience.job2.title': 'Designer de Produto',
      'about.experience.job2.company': 'Asksuite',
      'about.experience.job2.period': 'Jun 2024 – Mai 2026',
      'about.experience.job2.desc': 'Parte da liderança de produto do AskFlow Agents, uma plataforma B2B SaaS de automação com IA para hospitalidade, do pré-lançamento à escala — liderando discovery e desenhando builders de automação drag-and-drop e dashboards analíticos.',
      'about.experience.job3.title': 'Designer de Produto Sênior',
      'about.experience.job3.company': 'Vivo Telefônica',
      'about.experience.job3.period': 'Jul 2023 – Jun 2024',
      'about.experience.job3.desc': 'Liderei discovery e entrega de novas funcionalidades para uma plataforma B2B de e-commerce em uma das maiores teles do Brasil, estruturando testes assíncronos de usabilidade para acelerar decisões baseadas em dados.',
      'about.experience.job4.title': 'Designer de Produto Pleno',
      'about.experience.job4.company': 'Ília – Livelo',
      'about.experience.job4.period': 'Dez 2022 – Jun 2023',
      'about.experience.job4.desc': 'Conduzi a visão de produto de um produto B2B2C de e-commerce, liderando workshops de Lean Inception e sessões de co-criação com a Opportunity Tree de Teresa Torres — validado com 90% de compreensão em testes não moderados.',
      'about.experience.job5.title': 'Designer de Produto',
      'about.experience.job5.company': 'Take.blip',
      'about.experience.job5.period': 'Fev 2022 – Nov 2022',
      'about.experience.job5.desc': 'Desenhei um dashboard de analytics de consumo para uma solução financeira complexa, mapeando o fluxo de faturamento ponta a ponta — o lançamento gerou +3.500% de usuários ativos mensais e 80% de retenção.',
      'about.experience.job6.title': 'UX/UI Designer',
      'about.experience.job6.company': 'Tokenlab',
      'about.experience.job6.period': 'Fev 2021 – Fev 2022',
      'about.experience.job6.desc': 'Início de carreira em design de produto, construindo bases em pesquisa de usuário, prototipagem, design de interface e colaboração com times de desenvolvimento.',
      'about.education.title': 'Educação & Certificações',
      'about.education.degree1': 'Bacharelado em Arquitetura e Urbanismo',
      'about.education.university': 'Universidade de São Paulo (USP) • 2016–2022',
      'about.education.degree1.desc': 'Ênfase em Ciência da Computação (2018–2022). Foco em sistemas espaciais e resolução interdisciplinar de problemas.',
      'about.education.cert.title': 'Certificações',
      'about.education.cert.period': '2022–2023',
      'about.education.cert.desc': 'Scaling Design in Organizations (The Starter), Product Analytics (PM3), Jobs-to-Be-Done (Product Crafters).',
      'about.skills.title': 'Competências principais',
      'about.skills.item1': 'Estratégia de produto & discovery',
      'about.skills.item2': 'Design de interação',
      'about.skills.item3': 'Pesquisa qualitativa e quantitativa',
      'about.skills.item4': 'Design systems',
      'about.skills.item5': 'Fluxos complexos & UX de back-office',
      'about.skills.item6': 'Liderança cross-functional',
      'about.tools.title': 'Ferramentas',
      'about.tools.description': 'Figma, Sketch, Adobe XD, InVision, FigJam, Notion, Miro, Jira, Hotjar, Google Analytics, Mixpanel, Maze, Zeplin.',
      'about.languages.title': 'Idiomas',
      'about.languages.item1': 'Português — Nativo',
      'about.languages.item2': 'Inglês — Fluente (C2)',
      'about.languages.item3': 'Francês — Intermediário (B2)',
      'about.languages.item4': 'Espanhol — Básico (A2)',
      'about.languages.item5': 'Japonês — Básico (A1)',
      'contact.page.label': 'Contato',
      'contact.title': 'Vamos criar experiências cativantes juntos?',
      'contact.text': 'Seja para uma conversa sobre design de interação, estratégia de produto, ou uma oportunidade de colaboração, adoraria ouvir de você.',
      'contact.form.name': 'Nome',
      'contact.form.email': 'E-mail',
      'contact.form.message': 'Mensagem',
      'contact.form.placeholder.name': 'Seu nome',
      'contact.form.placeholder.email': 'voce@exemplo.com',
      'contact.form.placeholder.message': 'Fale sobre o produto, desafio ou oportunidade.',
      'contact.form.submit': 'Enviar mensagem',
      'contact.social.email': 'E-mail',
      'contact.social.linkedin': 'LinkedIn',
      'contact.social.phone': 'Telefone',
      'case-studies.page.label': 'Cases de estudo',
      'case-studies.title': 'Trabalhos selecionados na interseção entre design, estratégia e resultado de negócio.',
      'case-studies.text': 'Cada projeto explora um desafio diferente de produto, desde redesign de onboarding até dashboards densos em dados e ferramentas operacionais.',
      'case-studies.card.askflow.title': 'AskFlow Agent Library',
      'case-studies.card.askflow.desc': 'Simplificando a ativação para impulsionar o crescimento do negócio por meio de uma experiência de onboarding baseada em templates.',
      'case-studies.card.askflow.pill': 'AskFlow Agents • 2025',
      'case-studies.card.askflow.meta1': 'Design de Produto',
      'case-studies.card.askflow.meta2': '+40% de ativações',
      'case-studies.card.retail.title': 'Dashboard para triangulação de dados no varejo',
      'case-studies.card.retail.desc': 'Transformando a qualidade dos dados de checkout em uma superfície de decisão mais clara para estratégias de CRM com maior conversão.',
      'case-studies.card.retail.pill': 'Retail Data • 2024',
      'case-studies.card.retail.meta1': 'Estratégia UX',
      'case-studies.card.retail.meta2': 'Qualidade de dados',
      'case-studies.card.blip.title': 'Dashboard de cobrança e uso do WhatsApp',
      'case-studies.card.blip.desc': 'Consolidando métricas complexas de uso de SaaS em uma experiência intuitiva que reduziu atritos operacionais.',
      'case-studies.card.blip.pill': 'Blip • 2022',
      'case-studies.card.blip.meta1': 'Design de Produto',
      'case-studies.card.blip.meta2': 'Clareza operacional',
      'case.hero.label': 'Case Study',
      'case.hero.label.full': 'Case completo',
      'case.askflow.hero.title': 'AskFlow Agents: simplificando a ativação de fluxos de automação, do detalhe até a escala',
      'case.askflow.hero.subtitle': 'Como transformar um editor conversacional complexo em uma biblioteca de templates simplificada aumentou as ativações mensais em +40%.',
      'case.retail.hero.title': 'Triangulação de dados no varejo: transformando sinais de checkout em uma estratégia de CRM mais clara.',
      'case.retail.hero.subtitle': 'Como a criação de uma superfície analítica mais clara ajudou as equipes a identificar problemas de qualidade e melhorar a tomada de decisão.',
      'case.blip.hero.title': 'Dashboard de cobrança e uso do WhatsApp: transformando complexidade em confiança.',
      'case.blip.hero.subtitle': 'Como transformar dados fragmentados de uso de SaaS em uma interface mais clara ajudou equipes a reduzir esforço operacional.',
      'case.askflow.context.label': 'Contexto & Desafio',
      'case.askflow.context.heading': 'AskFlow é uma ferramenta drag-and-drop de IA conversacional para a indústria da hospitalidade. Após o lançamento, a adoção foi limitada por uma carga cognitiva alta e blocos de lógica intimidadores.',
      'case.askflow.problem.title': 'O problema',
      'case.askflow.problem.text': 'Os usuários podiam criar automações poderosas, mas a experiência parecia técnica demais para não desenvolvedores. O resultado foi ativação lenta, aumento de suporte e uma primeira impressão fraca.',
      'case.askflow.goals.title': 'Objetivos de design e negócio',
      'case.askflow.goals.item1': 'Reduzir o tempo até a percepção de valor',
      'case.askflow.goals.item2': 'Diminuir tickets de suporte',
      'case.askflow.goals.item3': 'Reduzir a carga cognitiva para usuários não técnicos',
      'case.askflow.metric.ticket.text': 'dos tickets do squad eram pedidos de mudança de agente.',
      'case.askflow.metric.activation.text': 'das contas foram ativadas nas primeiras 4 semanas.',
      'case.askflow.metric.setup.text': 'tempo médio de configuração por agente após o redesign.',
      'case.askflow.discovery.label': 'Descoberta & Estratégia',
      'case.askflow.discovery.heading': 'Alinhamos o triângulo de produto ao que importava: reduzir atrito mantendo flexibilidade.',
      'case.askflow.discovery.journey.title': 'Mapeamento da jornada',
      'case.askflow.discovery.journey.text': 'Mapeamos o caminho de ativação para descobrir onde os usuários travavam e quais suposições faltavam.',
      'case.askflow.discovery.workshops.title': 'Workshops com stakeholders',
      'case.askflow.discovery.workshops.text': 'Alinhamos design, produto e engenharia em oportunidades dignas de prioridade.',
      'case.askflow.discovery.csd.title': 'Matriz CSD',
      'case.askflow.discovery.csd.text': 'Usamos uma matriz de Certezas, Suposições e Dúvidas para focar o esforço em apostas de alta confiança.',
      'case.askflow.insight.label': 'Insight chave:',
      'case.askflow.insight.text': 'Mesmo fluxos customizados compartilham estruturas básicas. Uma Biblioteca de Templates de Agentes poderia reduzir atrito sem tirar flexibilidade.',
      'case.askflow.testing.label': 'Testes & Iteração',
      'case.askflow.testing.heading': 'O ponto de virada veio quando a experiência saiu de um construtor lotado para um playground guiado e mais calmo.',
      'case.askflow.testing.before.title': 'Antes',
      'case.askflow.testing.before.item1': 'Canvas drag-and-drop altamente desordenado',
      'case.askflow.testing.before.item2': 'Blocos visuais pesados e terminologia confusa',
      'case.askflow.testing.before.item3': 'Linguagem de lógica confusa como “Data de Referência”',
      'case.askflow.testing.after.title': 'Depois',
      'case.askflow.testing.after.item1': 'Blocos acinzentados e hierarquia mais limpa',
      'case.askflow.testing.after.item2': 'Sidebar contextual para entradas de dados',
      'case.askflow.testing.after.item3': 'Linguagem simplificada como “Momento de Referência”',
      'case.askflow.testing.supporting': 'Realizei duas rodadas de testes qualitativos com equipe interna e clientes de hotel. Os pontos de dor mais claros eram confusão em nomes de campos, descrições ocultas e lógica condicional mal compreendida como AND vs. OR.',
      'case.askflow.solution.label': 'A Solução',
      'case.askflow.solution.heading': 'Uma experiência de ativação orientada por biblioteca aliada a um editor mais calmo para usuários avançados.',
      'case.askflow.solution.library.title': 'Biblioteca de Agentes',
      'case.askflow.solution.library.text': 'Os usuários podiam navegar por agentes validados e ativá-los em menos de um minuto com configurações pré-definidas.',
      'case.askflow.solution.editor.title': 'Editor Contextual Refinado',
      'case.askflow.solution.editor.text': 'A superfície avançada permaneceu poderosa, mas visualmente muito menos ruidosa, ajudando os usuários a focar no que importava em seguida.',
      'case.askflow.outcomes.label': 'Resultados',
      'case.askflow.outcomes.heading': 'O redesign mostrou que reduzir a complexidade pode melhorar diretamente adoção e crescimento do negócio.',
      'case.askflow.outcomes.metric1.text': 'aumento nas ativações mensais em relação ao construtor anterior.',
      'case.askflow.outcomes.metric2.text': 'aumento na participação de receita HSM, alcançando 50/50 com a plataforma principal.',
      'case.askflow.outcomes.metric3.text': 'dos clientes geraram vendas usando um agente da biblioteca em até 30 dias.',
      'case.askflow.open-button': 'Acessar case completo',
      'case.askflow.open.title': 'Acessar case completo AskFlow',
      'case.askflow.open.description': 'Digite a senha para abrir o case completo do AskFlow Agents.',
      'case.blip.metric.complex.title': 'Complexo',
      'case.blip.metric.complex.text': 'dados de uso precisavam ser tornados compreensíveis sem perder precisão.',
      'case.blip.metric.clearer.title': 'Mais claro',
      'case.blip.metric.clearer.text': 'a estrutura reduziu a confusão para equipes operacionais e de suporte.',
      'case.blip.metric.faster.title': 'Mais rápido',
      'case.blip.metric.faster.text': 'a navegação ajudou os usuários a entender gastos e uso mais rapidamente.',
      'case.blip.context.label': 'Contexto',
      'case.blip.context.heading': 'A experiência original apresentava informações de uso e cobrança de forma fragmentada e difícil de escanear. As equipes precisavam de uma superfície operacional melhor.',
      'case.blip.challenge.title': 'Desafio',
      'case.blip.challenge.text': 'Os usuários precisavam juntar informações de várias áreas para entender o que estava acontecendo. O design precisava apoiar clareza e confiança.',
      'case.blip.solution.title': 'Solução',
      'case.blip.solution.item1': 'Organizei métricas chave em uma hierarquia mais clara',
      'case.blip.solution.item2': 'Reduzi o ruído visual e a carga cognitiva',
      'case.blip.solution.item3': 'Melhorei a escaneabilidade para tomada de decisão operacional',
      'case.blip.outcome.label': 'Resultado',
      'case.blip.outcome.heading': 'O dashboard ficou mais fácil de entender e melhor alinhado com fluxos de trabalho diários, o que aumentou confiança e reduziu atrito de suporte.',
      'case.blip.outcome.clarity.title': 'Clareza operacional',
      'case.blip.outcome.clarity.text': 'Guiou o usuário para as informações de cobrança e uso mais relevantes primeiro.',
      'case.blip.outcome.confidence.title': 'Confiança melhorada',
      'case.blip.outcome.confidence.text': 'Tornou a experiência mais confiável para uso frequente e revisão rápida.',
      'case.blip.open-button': 'Acessar case completo',
      'case.blip.open.title': 'Acessar case completo Blip',
      'case.blip.open.description': 'Digite a senha para abrir o case completo do dashboard da Blip.',
      'case.retail.metric.timeline.text': 'linha do tempo comprimida para um sprint de design de alto impacto.',
      'case.retail.metric.crunch.text': 'de trabalho intenso para validar e entregar a experiência.',
      'case.retail.metric.workflow.text': 'do fluxo de trabalho foi reestruturado em torno de sinais de decisão mais claros.',
      'case.retail.context.label': 'Contexto',
      'case.retail.context.heading': 'A equipe precisava de uma forma mais rápida de entender a qualidade dos dados de checkout sem se perder em dashboards fragmentados e métricas ruidosas.',
      'case.retail.challenge.title': 'Desafio',
      'case.retail.challenge.text': 'Os dados de varejo eram poderosos, mas difíceis de interpretar. O desafio era tornar a experiência mais acionável para equipes de CRM e comerciais trabalhando sob pressão.',
      'case.retail.approach.title': 'Abordagem',
      'case.retail.approach.item1': 'Priorizamos os sinais de qualidade mais críticos',
      'case.retail.approach.item2': 'Simplificamos a distribuição de dados pelo dashboard',
      'case.retail.approach.item3': 'Conectamos os dados a caminhos de decisão com maior conversão',
      'case.retail.solution.label': 'Solução',
      'case.retail.solution.heading': 'A experiência final agrupou sinais chave do varejo em um fluxo mais coerente, ajudando os usuários a julgar rapidamente se os dados eram confiáveis e úteis.',
      'case.retail.solution.unified.title': 'Visão unificada',
      'case.retail.solution.unified.text': 'Juntando indicadores de qualidade de checkout em uma interface gerenciável.',
      'case.retail.solution.faster.title': 'Decisões mais rápidas',
      'case.retail.solution.faster.text': 'Permitindo que as equipes identifiquem problemas de dados e próximos passos com menos atrito.',
      'case.retail.open-button': 'Acessar case completo',
      'case.retail.open.title': 'Acessar case completo Retail',
      'case.retail.open.description': 'Digite a senha para abrir o case completo do projeto de retail data.',
      'modal.restricted-access': 'Acesso restrito',
      'modal.access.title': 'Acessar case completo',
      'modal.access.description': 'Digite a senha para visualizar a versão completa do case.',
      'modal.password.label': 'Senha',
      'modal.password.placeholder': 'Digite a senha',
      'modal.submit': 'Acessar',
      'modal.request': 'Solicitar senha',
      'modal.error.invalid-password': 'Senha incorreta. Tente novamente ou solicite uma nova senha.',
      'modal.close.label': 'Fechar modal',
      'modal.request.subject': 'Solicitação de senha para case study',
      'modal.request.body': 'Olá, gostaria de receber a senha para acessar o case completo.',
      'case.askflow.full.hero.title': 'AskFlow Agents: da personalização à eficiência.',
      'case.askflow.full.hero.subtitle': 'Um walkthrough completo da estratégia de redesign, do processo de descoberta e do impacto no negócio por trás da experiência da Agent Library.',
      'case.retail.full.hero.title': 'Triangulação de dados no varejo: projetando para mais confiança na decisão.',
      'case.retail.full.hero.subtitle': 'Uma visão completa de como a experiência do dashboard foi reestruturada para tornar a qualidade dos dados de checkout mais fácil de interpretar.',
      'case.blip.full.hero.title': 'Dashboard de cobrança e uso do WhatsApp: transformando complexidade em confiança.',
      'case.blip.full.hero.subtitle': 'Uma versão completa da lógica de design por trás da reorganização de dados operacionais em uma experiência mais clara.',
      'case.askflow.preview.summary.label': 'Resumo executivo',
      'case.askflow.preview.summary.heading': 'O principal desafio era mover usuários de um construtor tecnicamente intimidador para um caminho de ativação mais rápido e confiável.',
      'case.askflow.preview.problem.title': 'Problema',
      'case.askflow.preview.problem.text': 'Embora a ferramenta fosse poderosa, o construtor drag-and-drop criava atrito demais para usuários não técnicos. A ativação caiu e a demanda por suporte aumentou.',
      'case.askflow.preview.strategy.title': 'Estratégia',
      'case.askflow.preview.strategy.text': 'Identificamos padrões comuns entre fluxos de trabalho e os transformamos em uma biblioteca de agentes pronta para uso que reduziu a necessidade de configuração manual.',
      'case.askflow.preview.impact.label': 'Impacto',
      'case.askflow.preview.impact.heading': 'O redesign melhorou a velocidade de ativação, reduziu o atrito de suporte e deixou o produto mais leve e acessível.',
      'case.askflow.preview.metric1.desc': 'aumento nas ativações mensais.',
      'case.askflow.preview.metric2.desc': 'tempo de configuração por agente.',
      'case.askflow.preview.metric3.desc': 'de clientes geraram vendas em até 30 dias usando a biblioteca.',
      'case.blip.preview.summary.label': 'Visão do projeto',
      'case.blip.preview.summary.heading': 'O dashboard precisava comunicar dados de cobrança e uso de modo calmo, estruturado e confiável para uso recorrente.',
      'case.blip.preview.decision.title': 'Decisão',
      'case.blip.preview.decision.text': 'Concentrei-me na hierarquia de informações, na escaneabilidade e em tornar os dados mais importantes fáceis de encontrar à primeira vista.',
      'case.blip.preview.value.title': 'Valor',
      'case.blip.preview.value.text': 'A experiência reduziu o atrito para usuários que precisavam entender gastos e uso rapidamente sem vasculhar camadas complexas.',
      'case.retail.preview.summary.label': 'Contexto',
      'case.retail.preview.summary.heading': 'O dashboard original sobrecarregava os usuários com sinais fragmentados e dificultava saber se os dados eram confiáveis.',
      'case.retail.preview.challenge.title': 'Desafio',
      'case.retail.preview.challenge.text': 'A equipe precisava de uma forma concisa de identificar problemas de qualidade no checkout e apoiar a estratégia de CRM sem explicações extras.',
      'case.retail.preview.result.title': 'Resultado',
      'case.retail.preview.result.text': 'A experiência foi redesenhada em torno de uma hierarquia mais clara de sinais, ajudando as equipes a ignorar o ruído e agir mais rápido.'
    },
    en: {
      'nav.home': 'Home',
      'nav.case-studies': 'Case Studies',
      'nav.about': 'About (CV)',
      'nav.contact': 'Contact',
      'case.back': 'Back',
      'page.title.home': 'Lari Toschi | UX & Product Designer',
      'page.title.case-studies': 'Case Studies | Lari Toschi',
      'page.title.about': 'About | Lari Toschi',
      'page.title.contact': 'Contact | Lari Toschi',
      'page.title.case-study': 'Case Study | Lari Toschi',
      'page.title.case-study-askflow': 'AskFlow Agents | Real case',
      'page.title.case-study-retail': 'Retail Data | Case Study',
      'page.title.case-study-blip': 'Blip | Real case',
      'page.title.case-askflow': 'AskFlow Agents • Full Case',
      'page.title.case-retail': 'Retail Data • Full Case',
      'page.title.case-blip': 'Blip • Full Case',
      'hero.eyebrow': 'Senior Product Designer • UX Strategy • UI',
      'hero.title': 'Hi, I’m Lari! I turn complex product flows into captivating user experiences.',
      'hero.text': 'I blend product strategy, interaction design, and behavioral insight to build products that feel intuitive and drive measurable growth.',
      'hero.cta.primary': 'View featured work',
      'hero.cta.secondary': 'Let’s talk',
      'home.about.label': 'About',
      'home.about.title': 'Architecture-trained, product-minded, tech-savvy and deeply curious about human behavior.',
      'home.about.text': 'With 5+ years of experience, I’ve worked across product strategy, usability, and growth-focused design in tech and B2B SaaS environments. Graduated in Architecture (USP), bringing a strong spatial and systems mindset into digital product design.',
      'home.featured.label': 'Featured Work',
      'home.featured.title': 'Selected cases that balance clarity, strategy, and measurable outcomes.',
      'home.featured.link': 'See all',
      'home.carousel.label': 'Image showcase',
      'home.carousel.title': 'Design samples and concept explorations.',
      'home.carousel.slide1.title': 'Product launch concept',
      'home.carousel.slide1.text': 'A visual exploration of launch messaging and content hierarchy in a modern product experience.',
      'home.carousel.slide1.cta': 'See more',
      'home.carousel.slide2.title': 'Interface exploration',
      'home.carousel.slide2.text': 'A sample concept emphasizing clarity, spacing, and content hierarchy across screens.',
      'home.carousel.slide2.cta': 'See more',
      'home.carousel.slide3.title': 'Dashboard preview',
      'home.carousel.slide3.text': 'A lightweight dashboard concept with a subtle overlay and quiet call to action.',
      'home.carousel.slide3.cta': 'See more',
      'home.featured.card.askflow.pill': 'AskFlow Agents',
      'home.featured.card.askflow.title': 'Simplifying AI activation to drive business growth',
      'home.featured.card.askflow.desc': 'Redesigned a complex conversational editor into a lightweight template library and boosted monthly activations by 40%.',
      'home.featured.card.askflow.meta1': '+40% monthly activations',
      'home.featured.card.askflow.meta2': 'Under 1 minute setup',
      'home.featured.card.askflow.meta3': 'Lower support load',
      'home.featured.card.blip.pill': 'Billing Dashboard',
      'home.featured.card.blip.title': 'Consolidating usage metrics into a clearer SaaS experience',
      'home.featured.card.blip.desc': 'Turned fragmented operational data into a clearer interface that reduced confusion and support overhead.',
      'home.featured.card.retail.pill': 'Retail Analytics',
      'home.featured.card.retail.title': 'Data triangulation for higher-converting CRM strategy',
      'home.featured.card.retail.desc': 'Shaped a retail dashboard to unify checkout signals and quality checks into a clearer decision surface.',
      'home.contact.label': 'Let’s connect',
      'home.contact.title': 'Open for freelancing and contract opportunities in senior product design where strategy, clarity, and growth meet.',
      'home.contact.cta': 'Contact me',
      'about.intro.label': 'About',
      'about.intro.title': 'Product designer with a systems lens and a human-centered approach.',
      'about.intro.text': 'Graduated in Architecture from USP with a minor on computer science. With 5+ years of UX and product experience, I bridge strategy, design, and implementation to build intuitive products that feel simple and scale well.',
      'about.profile.title': 'Currently based in',
      'about.profile.location': 'Taubaté, SP, Brazil',
      'about.profile.description': 'Lives with her husband and 4 cats. Loves psychology books, good coffee, and crisp micro-interactions.',
      'about.experience.title': 'Experience',
      'about.experience.job1.title': 'Senior Product Designer',
      'about.experience.job1.company': 'Omnichat',
      'about.experience.job1.period': 'May 2026 – Present',
      'about.experience.job1.desc': 'Designing the end-to-end experience for Whizz, an AI agent platform for e-commerce, making complex automation workflows and API-driven integrations accessible to non-technical users.',
      'about.experience.job2.title': 'Product Designer',
      'about.experience.job2.company': 'Asksuite',
      'about.experience.job2.period': 'Jun 2024 – May 2026',
      'about.experience.job2.desc': 'Part of the product leadership for AskFlow Agents, a B2B SaaS AI automation platform for hospitality, from pre-launch through scaling — leading discovery and designing drag-and-drop automation builders and analytics dashboards.',
      'about.experience.job3.title': 'Senior Product Designer',
      'about.experience.job3.company': 'Vivo Telefônica',
      'about.experience.job3.period': 'Jul 2023 – Jun 2024',
      'about.experience.job3.desc': 'Led discovery and delivery of new features for a B2B e-commerce platform at one of Brazil\'s largest telecom companies, structuring asynchronous usability testing to accelerate data-backed decisions.',
      'about.experience.job4.title': 'Mid-Level Product Designer',
      'about.experience.job4.company': 'Ília – Livelo',
      'about.experience.job4.period': 'Dec 2022 – Jun 2023',
      'about.experience.job4.desc': 'Owned the product vision for a B2B2C e-commerce product, leading Lean Inception workshops and co-creation sessions using Teresa Torres\' Opportunity Tree — validated with 90% user comprehension in unmoderated testing.',
      'about.experience.job5.title': 'Product Designer',
      'about.experience.job5.company': 'Take.blip',
      'about.experience.job5.period': 'Feb 2022 – Nov 2022',
      'about.experience.job5.desc': 'Designed a consumption analytics dashboard for a complex financial solution, mapping the end-to-end billing workflow — the launch drove a +3,500% increase in monthly active users and 80% retention.',
      'about.experience.job6.title': 'UX/UI Designer',
      'about.experience.job6.company': 'Tokenlab',
      'about.experience.job6.period': 'Feb 2021 – Feb 2022',
      'about.experience.job6.desc': 'Started my product design career, building foundational skills in user research, prototyping, interface design, and cross-functional collaboration with development teams.',
      'about.education.title': 'Education & Certifications',
      'about.education.degree1': 'Bachelor of Architecture & Urban Planning',
      'about.education.university': 'University of São Paulo (USP) • 2016–2022',
      'about.education.degree1.desc': 'Emphasis in Computer Science (2018–2022). Focused on spatial systems and interdisciplinary problem-solving.',
      'about.education.cert.title': 'Certifications',
      'about.education.cert.period': '2022–2023',
      'about.education.cert.desc': 'Scaling Design in Organizations (The Starter), Product Analytics (PM3), Jobs-to-Be-Done (Product Crafters).',
      'about.skills.title': 'Core Skills',
      'about.skills.item1': 'Product Strategy & Discovery',
      'about.skills.item2': 'Interaction Design',
      'about.skills.item3': 'Qualitative & Quantitative Research',
      'about.skills.item4': 'Design Systems',
      'about.skills.item5': 'Complex Workflow & Back-Office UX',
      'about.skills.item6': 'Cross-functional Leadership',
      'about.tools.title': 'Tools',
      'about.tools.description': 'Figma, Sketch, Adobe XD, InVision, FigJam, Notion, Miro, Jira, Hotjar, Google Analytics, Mixpanel, Maze, Zeplin.',
      'about.languages.title': 'Languages',
      'about.languages.item1': 'Portuguese — Native',
      'about.languages.item2': 'English — Fluent (C2)',
      'about.languages.item3': 'French — Intermediate (B2)',
      'about.languages.item4': 'Spanish — Basic (A2)',
      'about.languages.item5': 'Japanese — Basic (A1)',
      'contact.page.label': 'Contact',
      'contact.title': 'Let’s build something clear, useful, and memorable.',
      'contact.text': 'Whether it’s a product strategy conversation, a design leadership discussion, or a collaboration opportunity, I’d love to hear from you.',
      'contact.form.name': 'Name',
      'contact.form.email': 'Email',
      'contact.form.message': 'Message',
      'contact.form.placeholder.name': 'Your name',
      'contact.form.placeholder.email': 'you@example.com',
      'contact.form.placeholder.message': 'Tell me about the product, challenge, or opportunity.',
      'contact.form.submit': 'Send message',
      'contact.social.email': 'Email',
      'contact.social.linkedin': 'LinkedIn',
      'contact.social.phone': 'Phone',
      'modal.restricted-access': 'Restricted access',
      'modal.access.title': 'Access full case',
      'modal.access.description': 'Enter the password to open the full case.',
      'modal.password.label': 'Password',
      'modal.password.placeholder': 'Enter the password',
      'modal.submit': 'Access',
      'modal.request': 'Request password',
      'modal.error.invalid-password': 'Incorrect password. Please try again or request a new password.',
      'modal.close.label': 'Close modal',
      'modal.request.subject': 'Password request for case study',
      'modal.request.body': 'Hello, I would like to receive the password to access the full case.',
      'case-studies.page.label': 'Case Studies',
      'case-studies.title': 'Selected work at the intersection of clarity, strategy, and measurable growth.',
      'case-studies.text': 'Each project explores a different product challenge, from onboarding redesign to data-heavy dashboards and operational tooling.',
      'case-studies.card.askflow.title': 'AskFlow Agent Library',
      'case-studies.card.askflow.desc': 'Simplifying activation to drive business growth through a template-first onboarding experience.',
      'case-studies.card.askflow.pill': 'AskFlow Agents • 2025',
      'case-studies.card.askflow.meta1': 'Product Design',
      'case-studies.card.askflow.meta2': '+40% activations',
      'case-studies.card.retail.title': 'Dashboard for Data Triangulation in Retail',
      'case-studies.card.retail.desc': 'Transforming checkout data quality into a clearer decision surface for high-converting CRM approaches.',
      'case-studies.card.retail.pill': 'Retail Data • 2024',
      'case-studies.card.retail.meta1': 'UX Strategy',
      'case-studies.card.retail.meta2': 'Data quality',
      'case-studies.card.blip.title': 'WhatsApp Usage Billing Dashboard',
      'case-studies.card.blip.desc': 'Consolidating complex SaaS usage metrics into an intuitive experience that reduced operational friction.',
      'case-studies.card.blip.pill': 'Blip • 2022',
      'case-studies.card.blip.meta1': 'Product Design',
      'case-studies.card.blip.meta2': 'Operational clarity',
      'case.hero.label': 'Case Study',
      'case.hero.label.full': 'Full case',
      'case.askflow.hero.title': 'AskFlow Agents: Simplifying AI activation to drive business growth.',
      'case.askflow.hero.subtitle': 'How redesigning a complex drag-and-drop conversational editor into a simplified template library boosted monthly activations by +40%.',
      'case.retail.hero.title': 'Retail data triangulation: turning checkout signals into a better CRM strategy.',
      'case.retail.hero.subtitle': 'How designing a clearer analytics surface helped teams identify quality issues and improve decision-making.',
      'case.blip.hero.title': 'WhatsApp usage billing dashboard: simplifying a complex operational experience.',
      'case.blip.hero.subtitle': 'How turning fragmented SaaS usage data into a clearer interface helped teams reduce operational overhead.',
      'case.askflow.full.hero.title': 'AskFlow Agents: from personalization to efficiency.',
      'case.askflow.full.hero.subtitle': 'A complete walkthrough of the redesign strategy, discovery process, and business impact behind the Agent Library experience.',
      'case.retail.full.hero.title': 'Retail data triangulation: designing for faster decision confidence.',
      'case.retail.full.hero.subtitle': 'A complete view of how the dashboard experience was restructured to make checkout data quality easier to interpret.',
      'case.blip.full.hero.title': 'Blip usage billing dashboard: turning complexity into trust.',
      'case.blip.full.hero.subtitle': 'A full version of the design rationale behind reorganizing operational data into a clearer experience.',
      'case.askflow.context.label': 'Context & Challenge',
      'case.askflow.context.heading': 'AskFlow is a drag-and-drop conversational AI automation tool for the hospitality industry. Post-launch adoption was constrained by a high cognitive load and intimidating logic blocks.',
      'case.askflow.problem.title': 'The problem',
      'case.askflow.problem.text': 'Users could build powerful automations, but the experience felt too technical for non-developers. The result was slow activation, rising support demand, and a weak first impression.',
      'case.askflow.goals.title': 'Design & business goals',
      'case.askflow.goals.item1': 'Shorten time-to-perceived ROI',
      'case.askflow.goals.item2': 'Reduce support tickets',
      'case.askflow.goals.item3': 'Lower cognitive load for non-technical users',
      'case.askflow.metric.ticket.text': 'of squad tickets were requests for agent changes.',
      'case.askflow.metric.activation.text': 'of accounts were activated within the first 4 weeks.',
      'case.askflow.metric.setup.text': 'average setup time per agent after redesign.',
      'case.askflow.discovery.label': 'Discovery & Strategy',
      'case.askflow.discovery.heading': 'We aligned the product triad around what mattered most: reducing friction while preserving flexibility.',
      'case.askflow.discovery.journey.title': 'Journey Mapping',
      'case.askflow.discovery.journey.text': 'Mapped the activation path to uncover where users got stuck and what assumptions were missing.',
      'case.askflow.discovery.workshops.title': 'Stakeholder Workshops',
      'case.askflow.discovery.workshops.text': 'Aligned design, product, and engineering around opportunities worth prioritizing first.',
      'case.askflow.discovery.csd.title': 'CSD Matrix',
      'case.askflow.discovery.csd.text': 'Used a matrix of Certainties, Suppositions, and Doubts to focus the effort on high-confidence bets.',
      'case.askflow.insight.label': 'Key insight:',
      'case.askflow.insight.text': 'Even custom workflows share common baseline structures. A standard Agent Template Library could reduce friction without removing flexibility.',
      'case.askflow.testing.label': 'Testing & Iteration',
      'case.askflow.testing.heading': 'The turning point came when the experience moved from a crowded builder to a calmer, guided playground.',
      'case.askflow.testing.before.title': 'Before',
      'case.askflow.testing.before.item1': 'Highly cluttered drag-and-drop canvas',
      'case.askflow.testing.before.item2': 'Heavy visual blocks and noisy terminology',
      'case.askflow.testing.before.item3': 'Confusing logic language such as “Reference Date”',
      'case.askflow.testing.after.title': 'After',
      'case.askflow.testing.after.item1': 'Muted gray blocks and cleaner hierarchy',
      'case.askflow.testing.after.item2': 'Contextual sidebar for data inputs',
      'case.askflow.testing.after.item3': 'Simplified language such as “Reference Moment”',
      'case.askflow.testing.supporting': 'I ran two rounds of qualitative testing with internal staff and hotel clients. The clearest pain points were confusion around field names, hidden descriptions, and misunderstood conditional logic such as AND vs. OR.',
      'case.askflow.solution.label': 'The Solution',
      'case.askflow.solution.heading': 'A library-first activation experience paired with a calmer editor for advanced users.',
      'case.askflow.solution.library.title': 'Agent Showcase Library',
      'case.askflow.solution.library.text': 'Users could browse validated AI agents and activate them in less than a minute with predefined settings.',
      'case.askflow.solution.editor.title': 'Refined Contextual Editor',
      'case.askflow.solution.editor.text': 'The advanced editing surface stayed powerful but significantly less visually noisy, helping users focus on what mattered next.',
      'case.askflow.outcomes.label': 'Outcomes',
      'case.askflow.outcomes.heading': 'The redesign showed that reducing complexity can directly improve both user adoption and business growth.',
      'case.askflow.outcomes.metric1.text': 'increase in monthly activations compared to the previous builder.',
      'case.askflow.outcomes.metric2.text': 'growth in HSM revenue share, reaching a 50/50 split with the main platform.',
      'case.askflow.outcomes.metric3.text': 'of clients generated sales using an agent from the library within 30 days.',
      'case.askflow.open-button': 'Access full case',
      'case.askflow.open.title': 'Access full case AskFlow',
      'case.askflow.open.description': 'Enter the password to open the full AskFlow Agents case.',
      'case.blip.metric.complex.title': 'Complex',
      'case.blip.metric.complex.text': 'usage data had to be made understandable without losing precision.',
      'case.blip.metric.clearer.title': 'Clearer',
      'case.blip.metric.clearer.text': 'The structure reduced confusion for operational and support teams.',
      'case.blip.metric.faster.title': 'Faster',
      'case.blip.metric.faster.text': 'Navigation helped users understand spend and usage faster.',
      'case.blip.context.label': 'Context',
      'case.blip.context.heading': 'The original experience presented usage and billing information in a fragmented, hard-to-scan way. Teams needed a better operational surface.',
      'case.blip.challenge.title': 'Challenge',
      'case.blip.challenge.text': 'Users had to piece together information from multiple areas to understand what was happening. The design needed to support clarity and confidence.',
      'case.blip.solution.title': 'Solution',
      'case.blip.solution.item1': 'Organized key metrics into a clearer hierarchy',
      'case.blip.solution.item2': 'Reduced visual noise and cognitive load',
      'case.blip.solution.item3': 'Improved scanability for operational decision-making',
      'case.blip.outcome.label': 'Outcome',
      'case.blip.outcome.heading': 'The dashboard became easier to understand and better aligned with everyday workflows, which improved confidence and reduced support friction.',
      'case.blip.outcome.clarity.title': 'Operational clarity',
      'case.blip.outcome.clarity.text': 'Guided the user toward the most relevant billing and usage information first.',
      'case.blip.outcome.confidence.title': 'Improved confidence',
      'case.blip.outcome.confidence.text': 'Made the experience more trustworthy for frequent use and fast review.',
      'case.blip.open-button': 'Access full case',
      'case.blip.open.title': 'Access full case Blip',
      'case.blip.open.description': 'Enter the password to open the full Blip billing dashboard case.',
      'case.retail.metric.timeline.text': 'compressed timeline for a high-stakes design sprint.',
      'case.retail.metric.crunch.text': 'of focused crunch work to validate and deliver the experience.',
      'case.retail.metric.workflow.text': 'of the workflow was restructured around clearer decision signals.',
      'case.retail.context.label': 'Context',
      'case.retail.context.heading': 'The team needed a faster way to understand retail checkout data quality without getting lost in fragmented dashboards and noisy metrics.',
      'case.retail.challenge.title': 'Challenge',
      'case.retail.challenge.text': 'Retail data was powerful but hard to interpret. The challenge was to make the experience more actionable for CRM and commercial teams working under time pressure.',
      'case.retail.approach.title': 'Approach',
      'case.retail.approach.item1': 'Prioritized the most critical quality signals',
      'case.retail.approach.item2': 'Simplified data distribution across the dashboard',
      'case.retail.approach.item3': 'Connected data with high-converting decision paths',
      'case.retail.solution.label': 'Solution',
      'case.retail.solution.heading': 'The final experience grouped key retail signals into a more coherent flow, helping users quickly judge whether the data was trustworthy and useful.',
      'case.retail.solution.unified.title': 'Unified view',
      'case.retail.solution.unified.text': 'Bringing together checkout quality indicators into one manageable interface.',
      'case.retail.solution.faster.title': 'Faster decisions',
      'case.retail.solution.faster.text': 'Enabling stakeholders to identify data issues and next steps with less friction.',
      'case.retail.open-button': 'Access full case',
      'case.retail.open.title': 'Access full case Retail',
      'case.retail.open.description': 'Enter the password to open the full retail data case.',
      'case.askflow.preview.summary.label': 'Executive summary',
      'case.askflow.preview.summary.heading': 'The core challenge was to move users from a technically intimidating builder to a reassuring and fast activation path.',
      'case.askflow.preview.problem.title': 'The problem',
      'case.askflow.preview.problem.text': 'Even though the tool was powerful, the drag-and-drop builder created too much friction for non-technical users. Activation dropped and support demand grew.',
      'case.askflow.preview.strategy.title': 'Design strategy',
      'case.askflow.preview.strategy.text': 'We identified common baseline patterns across workflows and translated them into a curated library of ready-to-use agents that reduced the need for manual setup.',
      'case.askflow.preview.impact.label': 'Impact',
      'case.askflow.preview.impact.heading': 'The redesign improved activation speed, reduced support friction, and made the product feel lighter and more approachable.',
      'case.askflow.preview.metric1.desc': 'increase in monthly activations.',
      'case.askflow.preview.metric2.desc': 'setup time per agent.',
      'case.askflow.preview.metric3.desc': 'of clients generated sales within 30 days using the library.',
      'case.blip.preview.summary.label': 'Project view',
      'case.blip.preview.summary.heading': 'The dashboard needed to communicate billing and usage data in a way that felt calm, structured, and reliable for recurring use.',
      'case.blip.preview.decision.title': 'Decision',
      'case.blip.preview.decision.text': 'I focused on information hierarchy, scanability, and making the most critical data easy to find on first glance.',
      'case.blip.preview.value.title': 'Value',
      'case.blip.preview.value.text': 'The experience reduced friction for users who needed to understand spend and usage quickly without digging through complex layers.',
      'case.retail.preview.summary.label': 'Context',
      'case.retail.preview.summary.heading': 'The original dashboard overloaded users with fragmented signals and made it difficult to tell whether the data was trustworthy.',
      'case.retail.preview.challenge.title': 'Challenge',
      'case.retail.preview.challenge.text': 'The team needed a concise way to identify issues affecting checkout quality and to support CRM strategy without extra explanation.',
      'case.retail.preview.result.title': 'Result',
      'case.retail.preview.result.text': 'The experience was redesigned around a clearer hierarchy of signals, helping teams skip noise and act faster.'
    }
  };

  function applyLanguage(lang) {
    const selectedLang = translations[lang] ? lang : defaultLang;

    document.documentElement.lang = selectedLang;
    document.body.setAttribute('data-lang', selectedLang);

    const titleElement = document.querySelector('title[data-i18n-key]');
    if (titleElement) {
      const titleKey = titleElement.getAttribute('data-i18n-key');
      const translatedTitle = translations[selectedLang]?.[titleKey];

      if (translatedTitle) {
        titleElement.textContent = translatedTitle;
      }
    }

    document.querySelectorAll('[data-i18n-key]').forEach((element) => {
      const key = element.getAttribute('data-i18n-key');
      const translatedText = translations[selectedLang]?.[key];

      if (translatedText) {
        if (element.children.length > 0) {
          element.innerHTML = translatedText;
        } else {
          element.textContent = translatedText;
        }
      }
    });

    const attributeMappings = {
      'data-title-key': 'data-title',
      'data-description-key': 'data-description',
      'data-alt-key': 'alt',
      'data-aria-label-key': 'aria-label',
      'data-placeholder-key': 'placeholder'
    };

    Object.entries(attributeMappings).forEach(([keyAttr, targetAttr]) => {
      document.querySelectorAll(`[${keyAttr}]`).forEach((element) => {
        const translationKey = element.getAttribute(keyAttr);
        const translatedValue = translations[selectedLang]?.[translationKey];

        if (translatedValue) {
          element.setAttribute(targetAttr, translatedValue);
        }
      });
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => {
      const key = element.getAttribute('data-i18n-placeholder');
      const translatedPlaceholder = translations[selectedLang]?.[key];

      if (translatedPlaceholder) {
        element.placeholder = translatedPlaceholder;
      }
    });

    document.querySelectorAll('.lang-btn').forEach((button) => {
      const isActive = button.getAttribute('data-lang') === selectedLang;
      button.classList.toggle('active', isActive);
      button.setAttribute('aria-pressed', isActive ? 'true' : 'false');
    });

    window.getTranslation = function (key) {
      const currentLang = document.body.getAttribute('data-lang') || defaultLang;
      return translations[currentLang]?.[key] || '';
    };
  }

  function initCarousel() {
    const carousel = document.querySelector('[data-carousel]');
    if (!carousel) return;

    const slides = Array.from(carousel.querySelectorAll('.carousel-slide'));
    const prevButton = carousel.querySelector('.carousel-button.prev');
    const nextButton = carousel.querySelector('.carousel-button.next');
    const indicators = Array.from(carousel.querySelectorAll('.carousel-indicator'));
    let activeIndex = slides.findIndex((slide) => slide.classList.contains('active'));
    if (activeIndex < 0) activeIndex = 0;

    const updateState = (index) => {
      activeIndex = (index + slides.length) % slides.length;
      slides.forEach((slide, slideIndex) => {
        const isActive = slideIndex === activeIndex;
        slide.classList.toggle('active', isActive);
        slide.setAttribute('aria-hidden', (!isActive).toString());
      });
      indicators.forEach((indicator, indicatorIndex) => {
        const isActive = indicatorIndex === activeIndex;
        indicator.classList.toggle('active', isActive);
        indicator.setAttribute('aria-selected', isActive ? 'true' : 'false');
      });
    };

    prevButton?.addEventListener('click', () => updateState(activeIndex - 1));
    nextButton?.addEventListener('click', () => updateState(activeIndex + 1));
    indicators.forEach((indicator, index) => {
      indicator.addEventListener('click', () => updateState(index));
    });
  }

  const savedLang = window.localStorage.getItem(storageKey);
  const initialLang = savedLang && translations[savedLang] ? savedLang : defaultLang;
  applyLanguage(initialLang);
  initCarousel();

  document.addEventListener('click', (event) => {
    const button = event.target.closest('.lang-btn');
    if (!button) return;

    const selectedLang = button.getAttribute('data-lang');
    if (!selectedLang) return;

    window.localStorage.setItem(storageKey, selectedLang);
    applyLanguage(selectedLang);
  });
})();
