(function () {
  const storageKey = 'portfolio-language';
  const defaultLang = 'pt';
  const translations = {
    pt: {
      'nav.home': 'Início',
      'nav.case-studies': 'Cases',
      'nav.about': 'Sobre (CV)',
      'nav.contact': 'Contato',
      'case.back': 'Todos os cases',
      'page.title.home': 'Lari Toschi | Product Designer',
      'page.title.case-studies': 'Cases | Lari Toschi',
      'page.title.about': 'Sobre | Lari Toschi',
      'page.title.contact': 'Contato | Lari Toschi',
      'page.title.case-study': 'Case Study | Lari Toschi',
      'page.title.case-study-askflow': 'AskFlow Agents | Case Study',
      'page.title.case-study-retail': 'Retail Data | Case Study',
      'page.title.case-study-blip': 'Blip | Case Study',
      'page.title.case-arskflow': 'AskFlow Agents • Case Completo',
      'page.title.case-retail': 'Retail Data • Case Completo',
      'page.title.case-blip': 'Blip • Case Completo',
      'hero.eyebrow': 'Designer de Produto Pl/Sr • UX Research • UI Design',
      'hero.title': 'Olá, sou a Lari! Transformo problemas complexos em experiências envolventes.',
      'hero.text': 'Combino product strategy, design de interação e insight comportamental para criar produtos intuitivos e com impacto mensurável.',
      'hero.cta.primary': 'Ver cases em destaque',
      'hero.cta.secondary': 'Vamos conversar',
      'home.about.label': 'Sobre',
      'home.about.title': 'Formada em Arquitetura com ênfase em computação pela USP, foco em produto e muita curiosidade por comportamento humano.',
      'home.about.text': 'Com mais de 5 anos de experiência, atuo próxima à estratégia de negócio, mesclando usabilidade e design, com minha maior experiência em SaaS B2B.',
      'home.featured.label': 'Cases em destaque',
      'home.featured.title': 'Trabalhos selecionados que equilibram clareza, estratégia e resultado de negócio.',
      'home.featured.link': 'Ver tudo',
      'home.carousel.label': 'Galeria de imagens',
      'home.carousel.title': 'Exemplos de design e explorações de conceito.',
      'home.carousel.slide1.title': 'Conceito de lançamento de produto',
      'home.carousel.slide1.text': 'Uma exploração visual de mensagens de lançamento e hierarquia de conteúdo em uma experiência moderna.',
      'home.carousel.slide1.cta': 'Ver mais',
      'home.carousel.slide2.title': 'Exploração de interface',
      'home.carousel.slide2.text': 'Um conceito de interface que destaca clareza, espaçamento e hierarquia de conteúdo entre telas.',
      'home.carousel.slide2.cta': 'Ver mais',
      'home.carousel.slide3.title': 'Prévia de dashboard',
      'home.carousel.slide3.text': 'Um conceito de dashboard leve com overlay sutil e um botão discreto para ver mais.',
      'home.carousel.slide3.cta': 'Ver mais',
      'home.featured.card.askflow.pill': 'AskFlow Agents',
      'home.featured.card.askflow.title': 'Reduzindo a carga cognitiva para acelerar a ativação de fluxos de automação',
      'home.featured.card.askflow.desc': 'Redesenhei um editor conversacional complexo em uma biblioteca de templates leve que resultou em um aumento de 40% nas ativações mensais.',
      'home.featured.card.askflow.meta1': '+40% de ativações mensais',
      'home.featured.card.askflow.meta2': 'Configuração em menos de 1 minuto',
      'home.featured.card.askflow.meta3': 'Redução de tickets de suporte',
      'home.featured.card.blip.pill': 'Dashboard de uso e cobrança',
      'home.featured.card.blip.title': 'Consolidando métricas de uso em uma experiência SaaS mais clara',
      'home.featured.card.blip.desc': 'Transformei dados operacionais fragmentados em uma interface mais clara que reduziu confusão e custos de suporte.',
      'home.featured.card.retail.pill': 'Analytics de Varejo',
      'home.featured.card.retail.title': 'Triangulação de dados para uma estratégia de CRM mais conversora',
      'home.featured.card.retail.desc': 'Estruturei um dashboard de varejo para unificar sinais de checkout e verificações de qualidade em uma superfície de decisão mais clara.',
      'home.contact.label': 'Vamos conversar',
      'home.contact.title': 'Aberta para freelancing e disposta a conversar sobre oportunidades em product e UX design.',
      'home.contact.cta': 'Entre em contato',
      'about.intro.label': 'Sobre',
      'about.intro.title': 'Designer de produto com visão de sistemas e abordagem centrada no usuário.',
      'about.intro.text': 'Formada em Arquitetura pela USP com foco em computação. Com mais de 5 anos de experiência em UX e produto, conecto estratégia, design e implementação para construir produtos intuitivos, simples e escaláveis.',
      'about.profile.title': 'Atualmente baseada em',
      'about.profile.location': 'Taubaté, SP',
      'about.profile.description': 'Vive com o marido e seus 4 gatos. Ama livros de psicologia, café chique e design bem feito.',
      'about.experience.title': 'Experiência',
      'about.experience.job1.title': 'Designer de Produto Sênior',
      'about.experience.job1.company': 'Omnichat',
      'about.experience.job1.period': 'Mai 2026 – Atual',
      'about.experience.job1.desc': 'Desenhando a experiência end-to-end da Whizz, uma plataforma de agentes de IA para e-commerce, tornando fluxos complexos de automação e integrações via API acessíveis a usuários não técnicos.',
      'about.experience.job2.title': 'Designer de Produto',
      'about.experience.job2.company': 'Asksuite',
      'about.experience.job2.period': 'Jun 2024 – Mai 2026',
      'about.experience.job2.desc': 'Parte da liderança de produto do AskFlow Agents, uma plataforma B2B SaaS de automação com IA para hospitalidade, do pré-lançamento à escala — liderando discovery e desenhando builders de automação drag-and-drop e dashboards analíticos.',
      'about.experience.job3.title': 'Designer de Produto Sênior',
      'about.experience.job3.company': 'Vivo Telefônica',
      'about.experience.job3.period': 'Jul 2023 – Jun 2024',
      'about.experience.job3.desc': 'Liderei discovery e entrega de novas funcionalidades para uma plataforma B2B de e-commerce em uma das maiores teles do Brasil, estruturando testes assíncronos de usabilidade para acelerar decisões baseadas em dados.',
      'about.experience.job4.title': 'Designer de Produto Pleno',
      'about.experience.job4.company': 'Ília – Livelo',
      'about.experience.job4.period': 'Dez 2022 – Jun 2023',
      'about.experience.job4.desc': 'Conduzi a visão de produto de um produto B2B2C de e-commerce, liderando workshops de Lean Inception e sessões de co-criação com a Opportunity Tree de Teresa Torres — validado com 90% de compreensão em testes não moderados.',
      'about.experience.job5.title': 'Designer de Produto',
      'about.experience.job5.company': 'Take.blip',
      'about.experience.job5.period': 'Fev 2022 – Nov 2022',
      'about.experience.job5.desc': 'Desenhei um dashboard de analytics de consumo para uma solução financeira complexa, mapeando o fluxo de faturamento ponta a ponta — o lançamento gerou +3.500% de usuários ativos mensais e 80% de retenção.',
      'about.experience.job6.title': 'UX/UI Designer',
      'about.experience.job6.company': 'Tokenlab',
      'about.experience.job6.period': 'Fev 2021 – Fev 2022',
      'about.experience.job6.desc': 'Início de carreira em design de produto, construindo bases em pesquisa de usuário, prototipagem, design de interface e colaboração com times de desenvolvimento.',
      'about.education.title': 'Educação & Certificações',
      'about.education.degree1': 'Bacharelado em Arquitetura e Urbanismo',
      'about.education.university': 'Universidade de São Paulo (USP) • 2016–2022',
      'about.education.degree1.desc': 'Ênfase em Ciência da Computação (2018–2022). Foco em sistemas espaciais e resolução interdisciplinar de problemas.',
      'about.education.cert.title': 'Certificações',
      'about.education.cert.period': '2022–2023',
      'about.education.cert.desc': 'Scaling Design in Organizations (The Starter), Product Analytics (PM3), Jobs-to-Be-Done (Product Crafters).',
      'about.skills.title': 'Competências principais',
      'about.skills.item1': 'Estratégia de produto & discovery',
      'about.skills.item2': 'Design de interação',
      'about.skills.item3': 'Pesquisa qualitativa e quantitativa',
      'about.skills.item4': 'Design systems',
      'about.skills.item5': 'Fluxos complexos & UX de back-office',
      'about.skills.item6': 'Liderança cross-functional',
      'about.tools.title': 'Ferramentas',
      'about.tools.description': 'Figma, Sketch, Adobe XD, InVision, FigJam, Notion, Miro, Jira, Hotjar, Google Analytics, Mixpanel, Maze, Zeplin.',
      'about.languages.title': 'Idiomas',
      'about.languages.item1': 'Português — Nativo',
      'about.languages.item2': 'Inglês — Fluente (C2)',
      'about.languages.item3': 'Francês — Intermediário (B2)',
      'about.languages.item4': 'Espanhol — Básico (A2)',
      'about.languages.item5': 'Japonês — Básico (A1)',
      'contact.page.label': 'Contato',
      'contact.title': 'Vamos criar experiências cativantes juntos?',
      'contact.text': 'Seja para uma conversa sobre design de interação, estratégia de produto, ou uma oportunidade de colaboração, adoraria ouvir de você.',
      'contact.form.name': 'Nome',
      'contact.form.email': 'E-mail',
      'contact.form.message': 'Mensagem',
      'contact.form.placeholder.name': 'Seu nome',
      'contact.form.placeholder.email': 'voce@exemplo.com',
      'contact.form.placeholder.message': 'Fale sobre o produto, desafio ou oportunidade.',
      'contact.form.submit': 'Enviar mensagem',
      'contact.social.email': 'E-mail',
      'contact.social.linkedin': 'LinkedIn',
      'contact.social.phone': 'Telefone',
      'case-studies.page.label': 'Cases de estudo',
      'case-studies.title': 'Trabalhos selecionados na interseção entre design, estratégia e resultado de negócio.',
      'case-studies.text': 'Cada projeto explora um desafio diferente de produto, desde redesign de onboarding até dashboards densos em dados e ferramentas operacionais.',
      'case-studies.card.askflow.title': 'AskFlow Agent Library',
      'case-studies.card.askflow.desc': 'Simplificando a ativação para impulsionar o crescimento do negócio por meio de uma experiência de onboarding baseada em templates.',
      'case-studies.card.askflow.pill': 'AskFlow Agents • 2025',
      'case-studies.card.askflow.meta1': 'Design de Produto',
      'case-studies.card.askflow.meta2': '+40% de ativações',
      'case-studies.card.retail.title': 'Dashboard para triangulação de dados no varejo',
      'case-studies.card.retail.desc': 'Transformando a qualidade dos dados de checkout em uma superfície de decisão mais clara para estratégias de CRM com maior conversão.',
      'case-studies.card.retail.pill': 'Retail Data • 2024',
      'case-studies.card.retail.meta1': 'Estratégia UX',
      'case-studies.card.retail.meta2': 'Qualidade de dados',
      'case-studies.card.blip.title': 'Dashboard de cobrança e uso do WhatsApp',
      'case-studies.card.blip.desc': 'Consolidando métricas complexas de uso de SaaS em uma experiência intuitiva que reduziu atritos operacionais.',
      'case-studies.card.blip.pill': 'Blip • 2022',
      'case-studies.card.blip.meta1': 'Design de Produto',
      'case-studies.card.blip.meta2': 'Clareza operacional',
      'case.hero.label': 'Case summary',
      'case.hero.label.full': 'Case resumido',
      'case.askflow.hero.title': 'AskFlow Agents: simplificando a ativação de IA para impulsionar o crescimento do negócio.',
      'case.askflow.hero.subtitle': 'O redesign de um editor conversacional complexo com drag-and-drop, junto à criação de uma biblioteca simplificada de templates, aumentou as ativações mensais em 40%.',
      'case.retail.hero.title': 'Triangulação de dados no varejo: transformando sinais de checkout em uma estratégia de CRM mais clara.',
      'case.retail.hero.subtitle': 'Como a criação de uma superfície analítica mais clara ajudou as equipes a identificar problemas de qualidade e melhorar a tomada de decisão.',
      'case.blip.hero.title': 'Dashboard de cobrança e uso do WhatsApp: transformando complexidade em confiança.',
      'case.blip.hero.subtitle': 'Como transformar dados fragmentados de uso de SaaS em uma interface mais clara ajudou equipes a reduzir esforço operacional.',
      'case.blip.full.hero.title': 'Dashboard de cobrança e uso do WhatsApp: transformando complexidade em confiança.',
      'case.blip.full.hero.subtitle': 'Uma versão completa da lógica de design por trás da reorganização de dados operacionais em uma experiência mais clara.',
      'case.blip.metric.1': 'crescimento de acessos',
      'case.blip.metric.2': 'CSAT três meses após o lançamento',
      'case.blip.metric.3': 'pontuação SUS no protótipo',
      'case.askflow.context.label': 'Contexto & Desafio',
      'case.askflow.context.heading': 'AskFlow é uma ferramenta de automação conversacional com IA e drag-and-drop para a indústria da hospitalidade.',
      'case.askflow.problem.title': 'O problema principal',
      'case.askflow.problem.text': 'Após o lançamento, a adoção foi limitada pela alta carga cognitiva e por blocos de lógica intimidadores que exigiam conhecimento de programação. Os usuários podiam criar automações poderosas, mas a experiência parecia técnica demais para não desenvolvedores. O resultado foi uma ativação lenta, aumento da demanda por suporte e uma primeira impressão fraca.',
      'case.askflow.goals.title': 'Objetivos de design e negócio',
      'case.askflow.goals.item1': 'Reduzir o tempo até a percepção de retorno sobre o investimento',
      'case.askflow.goals.item2': 'Reduzir tickets de suporte',
      'case.askflow.goals.item3': 'Diminuir a carga cognitiva para usuários não técnicos',
      'case.askflow.metric.ticket.text': 'dos tickets da squad eram pedidos de alterações nos agentes antes do lançamento da biblioteca.',
      'case.askflow.metric.activation.text': 'das contas foram ativadas nas primeiras 4 semanas após o lançamento da biblioteca.',
      'case.askflow.metric.setup.text': 'tempo médio de configuração por agente após o redesign.',
      'case.askflow.discovery.label': 'Descoberta & Estratégia',
      'case.askflow.discovery.heading': 'Alinhamos a tríade de produto em torno do que mais importava: reduzir o atrito sem perder flexibilidade.',
      'case.askflow.discovery.text': 'Mapeamos o caminho de ativação para descobrir onde usuários externos e internos ficavam bloqueados e quais suposições estavam faltando.',
      'case.askflow.discovery.journey.title': 'Mapeamento da jornada',
      'case.askflow.discovery.journey.text': 'Mapeei o processo de ativação para descobrir onde estavam os principais gargalos, tanto de processos internos quanto em relação aos clientes. Foi possível concluir que o processo inicial, tanto para agentes padrão (mais simples) quanto para os personalizados tinham o mesmo processo inicial.',
      'case.askflow.discovery.workshops.title': 'Workshop com o time de ativação',
      'case.askflow.discovery.workshops.text': 'Alinhamos os times internos em torno das oportunidades que valia a pena priorizar primeiro.',
      'case.askflow.discovery.csd.title': 'Matriz CSD',
      'case.askflow.discovery.csd.text': 'Usamos uma matriz de Certezas, Suposições e Dúvidas para concentrar o esforço em apostas de alta confiança.',
      'case.askflow.insight.label': 'Insight-chave:',
      'case.askflow.insight.text': 'Mesmo fluxos personalizados compartilham estruturas básicas. Uma Biblioteca de Templates de Agentes poderia reduzir o atrito sem remover a flexibilidade.',
      'case.askflow.process.label': 'Processo de design',
      'case.askflow.process.heading': 'Dos rascunhos em papel a um wireframe testável, refinado por meio de brainstormings em grupo.',
      'case.askflow.process.sketch.title': 'Rascunhos em papel',
      'case.askflow.process.sketch.text': 'Primeiro, rascunhei o conceito à mão para pensar na solução e validar rapidamente a ideia com a tríade de produto.',
      'case.askflow.process.wireframe.title': 'Wireframe no Figma Make',
      'case.askflow.process.wireframe.text': 'A partir daí, construí um wireframe no Figma Make para testar a ferramenta e iterar em sessões de brainstorming em grupo.',
      'case.askflow.testing.label': 'Testes & Iteração',
      'case.askflow.testing.heading': 'O ponto de virada aconteceu quando a experiência passou de um construtor congestionado para um ambiente mais calmo e guiado.',
      'case.askflow.testing.before.title': 'Antes',
      'case.askflow.testing.before.item1': 'Canvas drag-and-drop complexo para o usuário sem conhecimento técnico',
      'case.askflow.testing.before.item2': 'Blocos visuais e personalização detalhada',
      'case.askflow.testing.before.item3': 'Necessidade de conhecimento de programação',
      'case.askflow.testing.after.title': 'Depois',
      'case.askflow.testing.after.item1': 'Biblioteca com agentes mais comuns',
      'case.askflow.testing.after.item2': 'Sugestão de templates para WhatsApp já configurados e validados com a Meta para ativação rápida',
      'case.askflow.testing.after.item3': 'Ativação em poucos cliques com as personalizações mais comuns na forma de dropdown',
      'case.askflow.testing.supporting': 'Realizei duas rodadas de testes qualitativos com colaboradores internos e clientes de hotéis. Os principais pontos de dificuldade foram a confusão em torno dos nomes dos campos, descrições ocultas e a lógica condicional mal compreendida, como AND versus OR.',
      'case.askflow.solution.label': 'A Solução',
      'case.askflow.solution.heading': 'Uma experiência de ativação baseada primeiro na biblioteca, acompanhada de um editor mais calmo para usuários avançados.',
      'case.askflow.solution.library.title': 'Biblioteca de agentes em destaque',
      'case.askflow.solution.library.text': 'Os usuários podiam navegar por agentes de IA validados e ativá-los em menos de um minuto com configurações predefinidas.',
      'case.askflow.solution.editor.title': 'Editor contextual refinado',
      'case.askflow.solution.editor.text': 'A superfície de edição avançada continuou poderosa, mas ficou significativamente menos ruidosa visualmente, ajudando os usuários a se concentrarem no próximo passo.',
      'askflow.carousel.slide1.title': 'Editor do AskFlow Agents após o redesign',
      'askflow.carousel.slide1.text': 'Codificação por cores mais suave, drag-and-drop aprimorado e descrições mais fáceis de entender.',
      'askflow.carousel.slide2.title': 'Biblioteca de agentes',
      'askflow.carousel.slide2.text': 'Ativação simples e acesso aos diferentes agentes disponíveis.',
      'askflow.carousel.slide3.title': 'Ativação de agente de automação',
      'askflow.carousel.slide3.text': 'Com templates pré-aprovados, o tempo de ativação caiu para 3 minutos.',
      'case.askflow.outcomes.label': 'Resultados',
      'case.askflow.outcomes.heading': 'O redesign mostrou que reduzir a complexidade pode melhorar diretamente adoção e crescimento do negócio.',
      'case.askflow.outcomes.metric1.text': 'aumento nas ativações mensais em relação a somente o drag and drop anterior.',
      'case.askflow.outcomes.metric2.text': 'aumento na participação de receita HSM, alcançando 50/50 com a plataforma principal.',
      'case.askflow.outcomes.metric3.text': 'dos clientes geraram vendas usando um agente da biblioteca em até 30 dias.',
      'case.askflow.outcomes.metric4.text': 'das ativações mensais foram através da nova biblioteca de agentes já no primeiro mês de lançamento.',
      'case.askflow.outcomes.metric5.text': 'tempo total da jornada, desde a entrada na biblioteca até a ativação de um agente.',
      'case.askflow.open-button': 'Acessar case completo',
      'case.askflow.open.title': 'Acessar case completo AskFlow',
      'case.askflow.open.description': 'Digite a senha para abrir o case completo do AskFlow Agents.',
      'case.blip.metric.complex.title': 'Complexo',
      'case.blip.metric.complex.text': 'dados de uso precisavam ser tornados compreensíveis sem perder precisão.',
      'case.blip.metric.clearer.title': 'Mais claro',
      'case.blip.metric.clearer.text': 'a estrutura reduziu a confusão para equipes operacionais e de suporte.',
      'case.blip.metric.faster.title': 'Mais rápido',
      'case.blip.metric.faster.text': 'a navegação ajudou os usuários a entender gastos e uso mais rapidamente.',
      'case.blip.context.label': 'Contexto',
      'case.blip.context.heading': 'Este case aconteceu na Blip, uma plataforma de criação de chatbots e empresa global de IA conversacional.',
      'case.blip.challenge.title': 'Desafio',
      'case.blip.challenge.text': 'Trabalhei na squad responsável pelos dados de consumo e cobrança. Os clientes só conseguiam acessar os dados de uso do plano em telas separadas, uma para cada métrica: usuários ativos diariamente, agentes e conversas no WhatsApp. Como a cobrança podia combinar várias dessas métricas, era necessário abrir várias abas para obter uma visão completa do uso. Isso dificultava o entendimento da cobrança e aumentava os tickets de suporte.',
      'case.blip.solution.title': 'Hipótese',
      'case.blip.solution.text1': 'Consolidar esses dados em um único dashboard reduziria as dúvidas dos clientes relacionadas à cobrança e teria impacto positivo na receita.',
      'case.blip.solution.text2': 'Esse dashboard se tornou o Relatório de Consumo.',
      'case.blip.discovery.title': 'Pesquisa',
      'case.blip.discovery.heading': 'Aprofundei-me no problema, combinando desk research sobre o uso existente, entrevistas qualitativas e um benchmark competitivo para entender como os clientes vivenciavam o acompanhamento de cobrança e consumo.',
      'case.blip.discovery.item1.title': 'Pesquisa com usuários internos',
      'case.blip.discovery.item1.text': 'A investigação interna resultou em um service blueprint que mapeou as operações de cobrança mais problemáticas.',
      'case.blip.discovery.item2.title': 'Entrevistas qualitativas',
      'case.blip.discovery.item2.text': 'Entrevistas semiestruturadas com 5 clientes que já usavam as telas de dados de consumo, para entender como acompanhavam o uso do plano.',
      'case.blip.discovery.item3.title': 'Benchmark de dashboards de uso',
      'case.blip.discovery.item3.text': 'Analisei aplicativos de acompanhamento de consumo, softwares de gestão financeira e plataformas concorrentes.',
      'case.blip.discovery.item4.title': 'Desk research',
      'case.blip.discovery.item4.text': 'Analisei dados já coletados com clientes, consolidados em um mapa de empatia e em um Point of View, revisados após as entrevistas.',
      'blip.carousel.slide1.title': 'Entrevistas qualitativas com clientes',
      'blip.carousel.slide1.text': 'Conduzi entrevistas semiestruturadas com 5 clientes para entender como acompanhavam o uso do plano e o que era mais relevante para eles.',
      'blip.carousel.slide2.title': 'Desk research + Point of View + mapa de empatia',
      'blip.carousel.slide2.text': 'Analisei dados já coletados com clientes e os consolidei, revisando-os após as entrevistas.',
      'blip.carousel.slide3.title': 'Benchmark e análise de dashboards de uso',
      'blip.carousel.slide3.text': 'Analisei aplicativos de acompanhamento de consumo, softwares de gestão financeira e plataformas concorrentes para entender como apresentavam dados de uso.',
      'case.blip.testing.label': 'Ideação e validação',
      'case.blip.testing.heading': 'Esbocei e prototipei formas de agrupar as métricas de consumo em um único dashboard. Depois, validei a demanda com um teste Wizard-of-Oz e refinei a solução por meio de testes de usabilidade moderados e uma pesquisa SUS.',
      'case.blip.testing.block1.title': 'Ideação',
      'case.blip.testing.block1.item1': 'Esbocei soluções no papel, mapeando quais telas e métricas deveriam ser agrupadas.',
      'case.blip.testing.block1.item2': 'Conduzi uma Design Critique com outros designers de produto para coletar feedback antes da prototipação.',
      'case.blip.testing.block1.item3': 'Construí um protótipo clicável inicial com um menu lateral para navegar pelas métricas, um bloco geral de status do plano com filtro mensal e seções dedicadas a cada métrica importante.',
      'case.blip.testing.block2.title': 'Validação',
      'case.blip.testing.block2.item1': 'Teste Wizard-of-Oz: como o custo de desenvolvimento era alto, testei a demanda antes de construir qualquer coisa. Enviei por e-mail um mock do relatório de consumo com uma pesquisa de feedback para 18 clientes selecionados.',
      'case.blip.testing.block2.item2': 'A porcentagem do plano consumida foi avaliada como a informação mais relevante. Os usuários ainda valorizavam os relatórios existentes de DAU, e a concentração dos dados agregou valor real.',
      'case.blip.testing.block2.item3': 'Teste de usabilidade moderado com 6 usuários e uma pesquisa SUS, que alcançou 82 pontos, bem acima da média de referência de 68.',
      'case.blip.testing.supporting': 'A maioria das falhas estava relacionada ao entendimento do card de Agentes. As menores pontuações foram atribuídas à consistência e à necessidade de conhecimento técnico para interpretar os nomes das métricas.',
      'case.blip.outcome.label': 'Resultado',
      'case.blip.outcome.heading': 'O dashboard ficou mais fácil de entender e mais alinhado aos fluxos de trabalho diários, melhorando a confiança e reduzindo o atrito com o suporte.',
      'case.blip.outcome.1.title': '+3.500% de crescimento nos acessos únicos mensais por cliente',
      'case.blip.outcome.1.text': 'Impulsionado por uma estratégia de onboarding via Appcues e campanhas de e-mail.',
      'case.blip.outcome.2.title': 'Maior confiança nos dados, apoiada pelo CSAT',
      'case.blip.outcome.2.text': 'No Appcues, entre 554 usuários exibidos e 5% de conclusão: 4,18/5 para clareza dos dados e 4,08/5 para utilidade no entendimento da cobrança.',
      'case.blip.outcome.3.title': 'Insight-chave para próximas iterações',
      'case.blip.outcome.3.text': 'Clientes com menor maturidade em dados tinham maior probabilidade de continuar com dificuldades para entender o modelo de cobrança, indicando que esse não era um problema pontual.',
      'case.blip.external.1.title': 'Acessar artigo na Central de Ajuda',
      'case.blip.open-button': 'Acessar case completo',
      'case.blip.open.title': 'Acessar case completo Blip',
      'case.blip.open.description': 'Digite a senha para abrir o case completo do dashboard da Blip.',
      'case.retail.metric.timeline.text': 'linha do tempo comprimida para um sprint de design de alto impacto.',
      'case.retail.metric.crunch.text': 'de trabalho intenso para validar e entregar a experiência.',
      'case.retail.metric.workflow.text': 'do fluxo de trabalho foi reestruturado em torno de sinais de decisão mais claros.',
      'case.retail.context.label': 'Contexto',
      'case.retail.context.heading': 'A equipe precisava de uma forma mais rápida de entender a qualidade dos dados de checkout sem se perder em dashboards fragmentados e métricas ruidosas.',
      'case.retail.challenge.title': 'Desafio',
      'case.retail.challenge.text': 'Os dados de varejo eram poderosos, mas difíceis de interpretar. O desafio era tornar a experiência mais acionável para equipes de CRM e comerciais trabalhando sob pressão.',
      'case.retail.approach.title': 'Abordagem',
      'case.retail.approach.item1': 'Priorizamos os sinais de qualidade mais críticos',
      'case.retail.approach.item2': 'Simplificamos a distribuição de dados pelo dashboard',
      'case.retail.approach.item3': 'Conectamos os dados a caminhos de decisão com maior conversão',
      'case.retail.solution.label': 'Solução',
      'case.retail.solution.heading': 'A experiência final agrupou sinais chave do varejo em um fluxo mais coerente, ajudando os usuários a julgar rapidamente se os dados eram confiáveis e úteis.',
      'case.retail.solution.unified.title': 'Visão unificada',
      'case.retail.solution.unified.text': 'Juntando indicadores de qualidade de checkout em uma interface gerenciável.',
      'case.retail.solution.faster.title': 'Decisões mais rápidas',
      'case.retail.solution.faster.text': 'Permitindo que as equipes identifiquem problemas de dados e próximos passos com menos atrito.',
      'case.retail.open-button': 'Acessar case completo',
      'case.retail.open.title': 'Acessar case completo Retail',
      'case.retail.open.description': 'Digite a senha para abrir o case completo do projeto de retail data.',
      'modal.restricted-access': 'Acesso restrito',
      'modal.access.title': 'Acessar case completo',
      'modal.access.description': 'Digite a senha para visualizar a versão completa do case.',
      'modal.password.label': 'Senha',
      'modal.password.placeholder': 'Digite a senha',
      'modal.submit': 'Acessar',
      'modal.request': 'Solicitar senha',
      'modal.error.invalid-password': 'Senha incorreta. Tente novamente ou solicite uma nova senha.',
      'modal.close.label': 'Fechar modal',
      'modal.request.subject': 'Solicitação de senha para case study',
      'modal.request.body': 'Olá, gostaria de receber a senha para acessar o case completo.',
      'case.askflow.full.hero.title': 'AskFlow Agents: da personalização à eficiência.',
      'case.askflow.full.hero.subtitle': 'Um walkthrough completo da estratégia de redesign, do processo de descoberta e do impacto no negócio por trás da experiência da Agent Library.',
      'case.retail.full.hero.title': 'Triangulação de dados no varejo: projetando para mais confiança na decisão.',
      'case.retail.full.hero.subtitle': 'Uma visão completa de como a experiência do dashboard foi reestruturada para tornar a qualidade dos dados de checkout mais fácil de interpretar.',
      'case.blip.full.hero.title': 'Dashboard de cobrança e uso do WhatsApp: transformando complexidade em confiança.',
      'case.blip.full.hero.subtitle': 'Uma versão completa da lógica de design por trás da reorganização de dados operacionais em uma experiência mais clara.',
      'case.askflow.preview.summary.label': 'Resumo executivo',
      'case.askflow.preview.summary.heading': 'O principal desafio era mover usuários de um construtor tecnicamente intimidador para um caminho de ativação mais rápido e confiável.',
      'case.askflow.preview.problem.title': 'Problema',
      'case.askflow.preview.problem.text': 'Embora a ferramenta fosse poderosa, o construtor drag-and-drop criava atrito demais para usuários não técnicos. A ativação caiu e a demanda por suporte aumentou.',
      'case.askflow.preview.strategy.title': 'Estratégia',
      'case.askflow.preview.strategy.text': 'Identificamos padrões comuns entre fluxos de trabalho e os transformamos em uma biblioteca de agentes pronta para uso que reduziu a necessidade de configuração manual.',
      'case.askflow.preview.impact.label': 'Impacto',
      'case.askflow.preview.impact.heading': 'O redesign melhorou a velocidade de ativação, reduziu o atrito de suporte e deixou o produto mais leve e acessível.',
      'case.askflow.preview.metric1.desc': 'aumento nas ativações mensais.',
      'case.askflow.preview.metric2.desc': 'tempo de configuração por agente.',
      'case.askflow.preview.metric3.desc': 'de clientes geraram vendas em até 30 dias usando a biblioteca.',
      'case.blip.preview.summary.label': 'Visão do projeto',
      'case.blip.preview.summary.heading': 'O dashboard precisava comunicar dados de cobrança e uso de modo calmo, estruturado e confiável para uso recorrente.',
      'case.blip.preview.decision.title': 'Decisão',
      'case.blip.preview.decision.text': 'Concentrei-me na hierarquia de informações, na escaneabilidade e em tornar os dados mais importantes fáceis de encontrar à primeira vista.',
      'case.blip.preview.value.title': 'Valor',
      'case.blip.preview.value.text': 'A experiência reduziu o atrito para usuários que precisavam entender gastos e uso rapidamente sem vasculhar camadas complexas.',
      'case.retail.preview.summary.label': 'Contexto',
      'case.retail.preview.summary.heading': 'O dashboard original sobrecarregava os usuários com sinais fragmentados e dificultava saber se os dados eram confiáveis.',
      'case.retail.preview.challenge.title': 'Desafio',
      'case.retail.preview.challenge.text': 'A equipe precisava de uma forma concisa de identificar problemas de qualidade no checkout e apoiar a estratégia de CRM sem explicações extras.',
      'case.retail.preview.result.title': 'Resultado',
      'case.retail.preview.result.text': 'A experiência foi redesenhada em torno de uma hierarquia mais clara de sinais, ajudando as equipes a ignorar o ruído e agir mais rápido.'
    },
    en: {
      'nav.home': 'Home',
      'nav.case-studies': 'Case Studies',
      'nav.about': 'About (CV)',
      'nav.contact': 'Contact',
      'case.back': 'All cases',
      'page.title.home': 'Lari Toschi ✷ product & ux designer 𖹭',
      'page.title.case-studies': 'Case Studies | Lari Toschi',
      'page.title.about': 'About | Lari Toschi',
      'page.title.contact': 'Contact | Lari Toschi',
      'page.title.case-study': 'Case Study | Lari Toschi',
      'page.title.case-study-askflow': 'AskFlow Agents ✷ Real case',
      'page.title.case-study-retail': 'Retail Data ✷ Case Study',
      'page.title.case-study-blip': 'Blip ✷ Case',
      'page.title.case-askflow': 'AskFlow Agents ✷ Full Case',
      'page.title.case-retail': 'Retail Data ✷ Case study',
      'page.title.case-blip': 'Blip ✷ Case',
      'hero.eyebrow': 'Product Designer • Service Design • Visual & UI Design',
      'hero.title': 'Hi, I’m Lari!',
      'hero.text1': 'I simplify complex B2B products for real users 𖹭',
      'hero.text2': 'From interface details to high-level strategy ✷ end-to-end UX & UI design',
      'hero.cta.primary': 'View featured work',
      'hero.cta.secondary': 'Let’s talk',
      'home.about.label': 'About',
      'home.about.title': 'Architecture-trained, product-minded, tech-savvy and deeply curious about human behavior.',
      'home.about.text': 'With 5+ years of experience, I’ve worked across B2B SaaS complex environments. Graduated in Architecture (USP) with a minor in computer science, I bring a strong spatial and systems mindset into digital product design.',
      'home.featured.label': 'Featured Work',
      'home.featured.title': 'Selected product design cases.',
      'home.featured.link': 'See all',
      /* CAROUSEL IGNORE START */
      'home.carousel.label': 'Image showcase',
      'home.carousel.title': 'Design samples and concept explorations.',
      'home.carousel.slide1.title': 'xxxx',
      'home.carousel.slide1.text': 'xxx',
      'home.carousel.slide1.cta': 'See more',
      'home.carousel.slide2.title': 'Interface exploration',
      'home.carousel.slide2.text': 'xxx',
      'home.carousel.slide2.cta': 'See more',
      'home.carousel.slide3.title': 'Dashboard preview',
      'home.carousel.slide3.text': 'xxxxx',
      'home.carousel.slide3.cta': 'See more',
      /* CAROUSEL IGNORE END */
      'home.featured.card.askflow.pill': 'AI & automation',
      'home.featured.card.askflow.title': 'Simplifying AI activation to drive business growth',
      'home.featured.card.askflow.desc': 'Redesigned a complex conversational editor into a lightweight template library and boosted monthly activations by 40%.',
      'home.featured.card.askflow.meta1': '+40% monthly activations',
      'home.featured.card.askflow.meta2': 'Under 1 minute setup',
      'home.featured.card.askflow.meta3': 'Lower support load',
      'home.featured.card.blip.pill': 'Data visualization',
      'home.featured.card.blip.title': 'Consolidating usage metrics into a clearer SaaS billing experience',
      'home.featured.card.blip.desc': 'Turned fragmented operational data into a clearer interface that improved billing transparency.',
      'home.featured.card.blip.meta1': '+3.500% monthly accesses',
      'home.featured.card.blip.meta2': 'Above 4 points in CSAT survey',
      'home.featured.card.blip.meta3': 'Wizard of Oz + Moderated user testing',
      'home.featured.card.retail.pill': 'Analytics case study',
      'home.featured.card.retail.title': 'Data triangulation for higher-converting CRM strategy',
      'home.featured.card.retail.desc': 'Shaped a retail dashboard to unify checkout signals and quality checks into a clearer decision surface.',
      'home.featured.card.retail.meta1': 'Design hackaton in 1 week',
      'home.featured.card.retail.meta2': 'Fast paced case',
      'home.featured.card.retail.meta3': 'Dashboard and drill-down data visualization',
      'home.contact.label': 'Let’s connect',
      'home.contact.title': 'Open for freelancing and remote contract opportunities in UX, UI and product design.',
      'home.contact.cta': 'Contact me',


      /* ABOUT PAGE */
      'about.intro.label': 'About',
      'about.intro.title1': 'from interface details to high-level strategy,',
      'about.intro.title2': 'I navigate product complexity with whimsy 𖹭',
      'about.intro.text': 'end-to-end UX/UI solutions for complex products ✷ from discovery to delivery',

      'about.profile.title': 'Find me (almost) everywhere',
      'about.profile.location': 'Taubaté, SP, Brazil',
      'about.profile.description': 'Remotely working worldwide, portuguese native and english fluent',

      'about.story.title': '5+ years designing complex B2B SaaS products',
      'about.story.p1': 'My path into product design started at the Universidade de São Paulo (USP), studying Architecture & Urban Planning alongside coursework in Computer Science. Designing physical structures taught me systemic thinking and spatial flow, while computing gave me technical logic. Today, I bring that exact hybrid perspective to solve unstructured B2B challenges.',
      'about.story.p2': 'In my most recent role at Omnichat, I owned UX for Whizz (Post-Sales), an AI agent platform for e-commerce. I maintained direct contact with clients to uncover operational friction and worked closely with technical and engineering teams to translate API integrations and multi-step AI automations into clear, effortless user journeys.',

      'about.pillars.title': 'How I approach design',
      'about.pillars.p1.title': 'Complexity and ambiguity = my favorite challenges',
      'about.pillars.p1.text': 'I specialize in turning dense data, backend logic, and API-driven workflows into clear, human-friendly interfaces.',
      'about.pillars.p2.title': 'Communication and team work are my strongest features',
      'about.pillars.p2.text': 'I bridge user needs with engineering constraints by staying close to customers and speaking fluent tech with developers.',
      'about.pillars.p3.title': 'My design flourish when I have access to data',
      'about.pillars.p3.text': 'I combine qualitative research, usability testing (Maze), and analytics (Hotjar, Mixpanel) to validate hypotheses and drive real business impact.',

      'about.exp.title': 'Past experiences',
      'about.exp.omnichat': 'Led end-to-end UX for Whizz (Post-Sales), AI Agent platform. Worked in direct contact with e-commerce clients and engineers to simplify complex automation workflows and API integrations.',
      'about.exp.asksuite': 'Designed AI automation tools (AskFlow Agents) for hospitality B2B SaaS, leading discovery and owning end-to-end interface design from drag-and-drop builders to operational dashboards.',
      'about.exp.vivo': 'Led discovery and UX optimization for enterprise B2B e-commerce sales funnels; scaled research through asynchronous Maze usability testing.',
      'about.exp.livelo': 'Facilitated Lean Inceptions and Teresa Torres Opportunity Trees to validate e-commerce features, achieving 90% user comprehension in testing.',
      'about.exp.blip': 'Designed consumption and billing dashboards for financial back-office; post-launch achieved a +3,500% MAU growth, 80% retention rate, and 82 SUS score.',


      'contact.page.label': 'Contact',
      'contact.title': 'Let’s build something clear, useful, and memorable.',
      'contact.text': 'Whether it’s a product strategy conversation, a design leadership discussion, or a collaboration opportunity, I’d love to hear from you.',
      'contact.form.name': 'Name',
      'contact.form.email': 'Email',
      'contact.form.message': 'Message',
      'contact.form.placeholder.name': 'Your name',
      'contact.form.placeholder.email': 'you@example.com',
      'contact.form.placeholder.message': 'Tell me about the product, challenge, or opportunity.',
      'contact.form.submit': 'Send message',
      'contact.social.email': 'Email',
      'contact.social.linkedin': 'LinkedIn',
      'contact.social.phone': 'Phone',
      'modal.restricted-access': 'Restricted access',
      'modal.access.title': 'Access full case',
      'modal.access.description': 'Enter the password to open the full case.',
      'modal.password.label': 'Password',
      'modal.password.placeholder': 'Enter the password',
      'modal.submit': 'Access',
      'modal.request': 'Request password',
      'modal.error.invalid-password': 'Incorrect password. Please try again or request a new password.',
      'modal.close.label': 'Close modal',
      'modal.request.subject': 'Password request for case study',
      'modal.request.body': 'Hello, I would like to receive the password to access the full case.',
      'case-studies.page.label': 'Case Studies',
      'case-studies.title': 'Selected work at the intersection of clarity, strategy, and measurable growth.',
      'case-studies.text': 'Each project explores a different product challenge, from onboarding redesign to data-heavy dashboards and operational tooling.',
      'case-studies.card.askflow.title': 'AskFlow Agent Library',
      'case-studies.card.askflow.desc': 'Simplifying activation to drive business growth through a template-first onboarding experience.',
      'case-studies.card.askflow.pill': 'AskFlow Agents • 2025',
      'case-studies.card.askflow.meta1': 'Product Design',
      'case-studies.card.askflow.meta2': '+40% activations',
      'case-studies.card.retail.title': 'Dashboard for Data Triangulation in Retail',
      'case-studies.card.retail.desc': 'Transforming checkout data quality into a clearer decision surface for high-converting CRM approaches.',
      'case-studies.card.retail.pill': 'Retail Data • 2024',
      'case-studies.card.retail.meta1': 'UX Strategy',
      'case-studies.card.retail.meta2': 'Data quality',
      'case-studies.card.blip.title': 'WhatsApp Usage Billing Dashboard',
      'case-studies.card.blip.desc': 'Consolidating complex SaaS usage metrics into an intuitive experience that reduced operational friction.',
      'case-studies.card.blip.pill': 'Blip • 2022',
      'case-studies.card.blip.meta1': 'Product Design',
      'case-studies.card.blip.meta2': 'Operational clarity',
      'case.hero.label': 'Case summary',
      'case.hero.label.full': 'Full case',
            'case.askflow.full.hero.title': 'AskFlow Agents: from personalization to efficiency.',
      'case.askflow.full.hero.subtitle': 'A complete walkthrough of the redesign strategy, discovery process, and business impact behind the Agent Library experience.',
/* ASKFLOW */
      'case.askflow.hero.title': 'AskFlow Agents: Simplifying AI activation to drive business growth.',
      'case.askflow.hero.subtitle': 'Redesigning of a complex drag-and-drop conversational editor + creating a simplified template library boosted monthly activations by +40%',
      'case.askflow.metric.ticket.text': 'of squad tickets were requests for agent changes pre-library launch.',
      'case.askflow.metric.activation.text': 'of accounts were activated within the first 4 weeks post library launch.',
      'case.askflow.metric.setup.text': 'average setup time per agent after redesign.',
      'case.askflow.context.label': 'Context & Challenge',
      'case.askflow.context.heading': 'AskFlow is a drag-and-drop conversational AI automation tool for the hospitality industry.',
      'case.askflow.problem.title': 'Main problem',
      'case.askflow.problem.text': 'Post-launch adoption was constrained by a high cognitive load and intimidating logic blocks that required programming knowledge. Users could build powerful automations, but the experience felt too technical for non-developers. The result was slow activation, rising support demand, and a weak first impression.',
      'case.askflow.goals.title': 'Design & business goals',
      'case.askflow.goals.item1': 'Shorten time-to-perceived ROI',
      'case.askflow.goals.item2': 'Reduce support tickets',
      'case.askflow.goals.item3': 'Lower cognitive load for non-technical users',
  
      'case.askflow.discovery.label': 'Discovery & Strategy',
      'case.askflow.discovery.heading': 'We aligned the product triad around what mattered most: reducing friction while preserving flexibility.',
      'case.askflow.discovery.journey.title': 'Journey Mapping',
      'case.askflow.discovery.journey.text': 'Mapped the activation path to uncover where external and internal users got stuck and what assumptions were missing.',
      'case.askflow.discovery.workshops.title': 'Activation team workshop',
      'case.askflow.discovery.workshops.text': 'Aligned internal teams around opportunities worth prioritizing first.',
      'case.askflow.discovery.csd.title': 'CSD Matrix',
      'case.askflow.discovery.csd.text': 'Used a matrix of Certainties, Suppositions, and Doubts to focus the effort on high-confidence bets.',
      'case.askflow.insight.label': 'Key insight:',
      'case.askflow.insight.text': 'Even custom workflows share common baseline structures. A standard Agent Template Library could reduce friction without removing flexibility.',
      'case.askflow.process.label': 'Design process',
      'case.askflow.process.heading': 'From paper sketches to a testable wireframe, refined through group brainstorming.',
      'case.askflow.process.sketch.title': 'Paper sketches',
      'case.askflow.process.sketch.text': 'I first sketched the concept by hand to think through and quickly validate the idea with the product triad.',
      'case.askflow.process.wireframe.title': 'Figma Make wireframe',
      'case.askflow.process.wireframe.text': 'From there, I built a wireframe in Figma Make to test the tool and iterate through group brainstorming sessions.',
      
      'case.askflow.testing.label': 'Testing & Iteration',
      'case.askflow.testing.heading': 'The turning point came when the experience moved from a crowded builder to a calmer, guided playground.',
      'case.askflow.testing.before.title': 'Before',
      'case.askflow.testing.before.item1': 'Highly cluttered drag-and-drop canvas',
      'case.askflow.testing.before.item2': 'Heavy visual blocks and noisy terminology',
      'case.askflow.testing.before.item3': 'Confusing logic language such as “Reference Date”',
      'case.askflow.testing.after.title': 'After',
      'case.askflow.testing.after.item1': 'Muted gray blocks and cleaner hierarchy',
      'case.askflow.testing.after.item2': 'Contextual sidebar for data inputs',
      'case.askflow.testing.after.item3': 'Simplified language such as “Reference Moment”',
      'case.askflow.testing.supporting': 'I ran two rounds of qualitative testing with internal staff and hotel clients. The clearest pain points were confusion around field names, hidden descriptions, and misunderstood conditional logic such as AND vs. OR.',
      'case.askflow.solution.label': 'The Solution',
      'case.askflow.solution.heading': 'A library-first activation experience paired with a calmer editor for advanced users.',
      'case.askflow.solution.library.title': 'Agent Showcase Library',
      'case.askflow.solution.library.text': 'Users could browse validated AI agents and activate them in less than a minute with predefined settings.',
      'case.askflow.solution.editor.title': 'Refined Contextual Editor',
      'case.askflow.solution.editor.text': 'The advanced editing surface stayed powerful but significantly less visually noisy, helping users focus on what mattered next.',
      /* carousel solution */
      'askflow.carousel.slide1.title': 'AskFlow Agents Editor post redesign',
      'askflow.carousel.slide1.text': 'Softer color-coding, improved drag and drop and more user friendly descriptions',
      'askflow.carousel.slide2.title': 'Agent library',
      'askflow.carousel.slide2.text': 'Easy activation and access to different agents available',
      'askflow.carousel.slide3.title': 'Automation agent activation',
      'askflow.carousel.slide3.text': 'With pre-approved templates, the activation time droped to 3 minutes',
      
      'case.askflow.outcomes.label': 'Outcomes',
      'case.askflow.outcomes.heading': 'The redesign showed that reducing complexity can directly improve both user adoption and business growth.',
      'case.askflow.outcomes.metric1.text': 'increase in monthly activations compared to the previous builder.',
      'case.askflow.outcomes.metric2.text': 'growth in HSM revenue share, reaching a 50/50 split with the main platform.',
      'case.askflow.outcomes.metric3.text': 'of clients generated sales using an agent from the library within 30 days.',
      'case.askflow.outcomes.metric4.text': 'of activations in the launch month came through the new agent library.',
      'case.askflow.outcomes.metric5.text': 'total journey time, from entering the library to activating an agent.',
      'case.askflow.open-button': 'Access full case',
      'case.askflow.open.title': 'Access full case AskFlow',
      'case.askflow.open.description': 'Coming soon!',
      
      'case.askflow.ending.label': '',
      'case.askflow.ending.heading': '',
      'case.askflow.ending.text': '',
      'case.askflow.article.1': '',
      'case.askflow.article.2': '',
      'case.askflow.article.3': '',

      /*RETAIL*/
      'case.retail.hero.title': 'Retail data triangulation: turning checkout signals into a better CRM strategy.',
      'case.retail.hero.subtitle': 'How designing a clearer analytics surface helped teams identify quality issues and improve decision-making.',
      'case.retail.full.hero.title': 'Retail data triangulation: designing for faster decision confidence.',
      'case.retail.full.hero.subtitle': 'A complete view of how the dashboard experience was restructured to make checkout data quality easier to interpret.',

      /*BLIP*/
      'case.blip.hero.title': 'WhatsApp usage billing dashboard: simplifying a complex operational experience.',
      'case.blip.hero.subtitle': 'How turning fragmented SaaS usage data into a clearer interface helped teams reduce operational overhead.',
      'case.blip.full.hero.title': 'Blip usage billing dashboard: turning complexity into trust.',
      'case.blip.full.hero.subtitle': 'A full version of the design rationale behind reorganizing operational data into a clearer experience.',

      'case.blip.metric.1': 'access growth',
      'case.blip.metric.2': 'CSAT 3-month post lauch',
      'case.blip.metric.3': 'SUS score on prototype',
      'case.blip.context.label': 'Context',
      'case.blip.context.heading': 'This case took place on a chatbot creation platform, Blip, a global Conversational AI company.',
      'case.blip.challenge.title': 'Challenge',
      'case.blip.challenge.text': 'I worked on the squad responsible for consumption data and billing. Clients could only access plan usage data through separate screens — one per metric (daily active users, agents, WhatsApp conversations). Since billing could combine several of these metrics, clients had to open multiple tabs to get a full picture of their usage, which made billing hard to understand and drove up support tickets.',
      'case.blip.solution.title': 'Hypothesis',
      'case.blip.solution.text1': 'Consolidating this data into a single dashboard would reduce clients billing-related doubts and positively impact revenue.',
      'case.blip.solution.text2': 'This dashboard became the Consumption Report.',


      'case.blip.discovery.title': 'Research',
      'case.blip.discovery.heading': 'I dived deep in problem-space, combined desk research on existing usage, qualitative interviews and a competitive benchmark to understand how clients experienced billing and consumption tracking.',
      'case.blip.discovery.item1.title': 'Internal users research',
      'case.blip.discovery.item1.text': 'Internal investigation resulted in a service blueprint mapping most problematic billing operations',
      'case.blip.discovery.item2.title': 'Qualitative interviews',
      'case.blip.discovery.item2.text': 'Semi-structured interviews with 5 clients who already used the consumption data screens, to understand how they tracked plan usage',
      'case.blip.discovery.item3.title': 'Benchmarking of usage dashboards',
      'case.blip.discovery.item3.text': 'Reviewed consumption-tracking apps, financial management software, and competing platforms',
      'case.blip.discovery.item4.title': 'Desk research',
      'case.blip.discovery.item4.text': 'Analyzed data already collected from clients, consolidated into an empathy map and a Point of View, reviewing it post interviews',
      
      'blip.carousel.slide1.title': 'Qualitative interviews with clients',
      'blip.carousel.slide1.text': 'I conducted semi-structured interviews with 5 clients to understand how they tracked plan usage and what was most relevant to them.',
      'blip.carousel.slide2.title': 'Desk research + Point of View + Empathy map',
      'blip.carousel.slide2.text': 'Analysis of data already collected from clients, consolidated, reviewing it post interviews',
      'blip.carousel.slide3.title': 'Benchmark and analysis of usage dashboards',
      'blip.carousel.slide3.text': 'Reviewed consumption-tracking apps, financial management software, and competing platforms to understand how they presented usage data.',

      'case.blip.testing.label': 'Ideation and validation',
      'case.blip.testing.heading': 'I sketched and prototyped ways to group consumption metrics into a single dashboard, then validated demand with a Wizard-of-Oz test and refined through moderated usability testing and a SUS survey.',
      'case.blip.testing.block1.title': 'Ideation',
      'case.blip.testing.block1.item1': 'Sketched solutions on paper, mapping which screens/metrics should be grouped',
      'case.blip.testing.block1.item2': 'Ran a Design Critique with other product designers to gather feedback before prototyping',
      'case.blip.testing.block1.item3': 'Built an initial clickable prototype: a side menu for navigating metrics, a general plan status block with a month filter, and dedicated sections for each important metric.',
      'case.blip.testing.block2.title': 'Validation',
      'case.blip.testing.block2.item1': 'Wizard-of-Oz test: since development cost was high, tested demand before building anything. Sent 18 selected clients an emailed mock consumption report with a feedback survey.',
      'case.blip.testing.block2.item2': '-> % of plan consumed was rated the most relevant info, users still valued the existing DAU reports and concentrating data added real value.',
      'case.blip.testing.block2.item3': 'Moderated usability testing with 6 users and a SUS survey (82 score, well above 68 benchmark average)',
      'case.blip.testing.supporting': 'Most failures centered on understanding the Agents card; lowest scores were on consistency and on needing technical knowledge to interpret metric names.',

      'case.blip.outcome.label': 'Outcome',
      'case.blip.outcome.heading': 'The dashboard became easier to understand and better aligned with everyday workflows, which improved confidence and reduced support friction.',
      'case.blip.outcome.1.title': '+3.500% growth in monthly unique accesses per client',
      'case.blip.outcome.1.text': 'driven by an onboarding strategy (via Appcues) and email marketing.',
      'case.blip.outcome.2.title': 'Improved confidence on data supported by CSAT score',
      'case.blip.outcome.2.text': 'Via Appcues, 554 users shown, 5% completion): 4.18/5 on data clarity, 4.08/5 on usefulness for understanding billing',
      'case.blip.outcome.3.title': 'Key insight for future iterations' ,
      'case.blip.outcome.3.text': 'Clients with lower data maturity were more likely to still struggle with understanding the billing model — signaling this wasnt a one-and-done problem.',
      
      'case.blip.ending.label': 'Reflection & other links',
      'case.blip.ending.heading': 'This work reinforces the need of research and validation to create a real end-to-end experience for users',
      'case.blip.ending.text': 'This is one of my most complete and end-to-end cases, envolving research with clients and internal collaborators. Also, learning about the varios depths of data literacy in B2B ambiance was extremely valuable for me as designer.',
      'case.blip.article.1': 'Help center Article: How to access the Consumption Report',
      'case.blip.article.2': 'Beta: How to access and users feedback',
      'case.blip.article.3': 'Help center Article: Consumption report how to use it',

      /* RETAIL */
      'case.retail.metric.timeline.text': 'compressed timeline for a high-stakes design sprint.',
      'case.retail.metric.crunch.text': 'of focused crunch work to validate and deliver the experience.',
      'case.retail.metric.workflow.text': 'of the workflow was restructured around clearer decision signals.',
      'case.retail.context.label': 'Context',
      'case.retail.context.heading': 'The team needed a faster way to understand retail checkout data quality without getting lost in fragmented dashboards and noisy metrics.',
      'case.retail.challenge.title': 'Challenge',
      'case.retail.challenge.text': 'Retail data was powerful but hard to interpret. The challenge was to make the experience more actionable for CRM and commercial teams working under time pressure.',
      'case.retail.approach.title': 'Approach',
      'case.retail.approach.item1': 'Prioritized the most critical quality signals',
      'case.retail.approach.item2': 'Simplified data distribution across the dashboard',
      'case.retail.approach.item3': 'Connected data with high-converting decision paths',
      'case.retail.solution.label': 'Solution',
      'case.retail.solution.heading': 'The final experience grouped key retail signals into a more coherent flow, helping users quickly judge whether the data was trustworthy and useful.',
      'case.retail.solution.unified.title': 'Unified view',
      'case.retail.solution.unified.text': 'Bringing together checkout quality indicators into one manageable interface.',
      'case.retail.solution.faster.title': 'Faster decisions',
      'case.retail.solution.faster.text': 'Enabling stakeholders to identify data issues and next steps with less friction.',
      'case.retail.open-button': 'Access full case',
      'case.retail.open.title': 'Access full case Retail',
      'case.retail.open.description': 'Enter the password to open the full retail data case.',
      'case.askflow.preview.summary.label': 'Executive summary',
      'case.askflow.preview.summary.heading': 'The core challenge was to move users from a technically intimidating builder to a reassuring and fast activation path.',
      'case.askflow.preview.problem.title': 'The problem',
      'case.askflow.preview.problem.text': 'Even though the tool was powerful, the drag-and-drop builder created too much friction for non-technical users. Activation dropped and support demand grew.',
      'case.askflow.preview.strategy.title': 'Design strategy',
      'case.askflow.preview.strategy.text': 'We identified common baseline patterns across workflows and translated them into a curated library of ready-to-use agents that reduced the need for manual setup.',
      'case.askflow.preview.impact.label': 'Impact',
      'case.askflow.preview.impact.heading': 'The redesign improved activation speed, reduced support friction, and made the product feel lighter and more approachable.',
      'case.askflow.preview.metric1.desc': 'increase in monthly activations.',
      'case.askflow.preview.metric2.desc': 'setup time per agent.',
      'case.askflow.preview.metric3.desc': 'of clients generated sales within 30 days using the library.',
      'case.blip.preview.summary.label': 'Project view',
      'case.blip.preview.summary.heading': 'The dashboard needed to communicate billing and usage data in a way that felt calm, structured, and reliable for recurring use.',
      'case.blip.preview.decision.title': 'Decision',
      'case.blip.preview.decision.text': 'I focused on information hierarchy, scanability, and making the most critical data easy to find on first glance.',
      'case.blip.preview.value.title': 'Value',
      'case.blip.preview.value.text': 'The experience reduced friction for users who needed to understand spend and usage quickly without digging through complex layers.',
      'case.retail.preview.summary.label': 'Context',
      'case.retail.preview.summary.heading': 'The original dashboard overloaded users with fragmented signals and made it difficult to tell whether the data was trustworthy.',
      'case.retail.preview.challenge.title': 'Challenge',
      'case.retail.preview.challenge.text': 'The team needed a concise way to identify issues affecting checkout quality and to support CRM strategy without extra explanation.',
      'case.retail.preview.result.title': 'Result',
      'case.retail.preview.result.text': 'The experience was redesigned around a clearer hierarchy of signals, helping teams skip noise and act faster.'
    }
  };

  function applyLanguage(lang) {
    const selectedLang = translations[lang] ? lang : defaultLang;

    document.documentElement.lang = selectedLang;
    document.body.setAttribute('data-lang', selectedLang);

    const titleElement = document.querySelector('title[data-i18n-key]');
    if (titleElement) {
      const titleKey = titleElement.getAttribute('data-i18n-key');
      const translatedTitle = translations[selectedLang]?.[titleKey];

      if (translatedTitle) {
        titleElement.textContent = translatedTitle;
      }
    }

    document.querySelectorAll('[data-i18n-key]').forEach((element) => {
      const key = element.getAttribute('data-i18n-key');
      const translatedText = translations[selectedLang]?.[key];

      if (translatedText) {
        if (element.children.length > 0) {
          element.innerHTML = translatedText;
        } else {
          element.textContent = translatedText;
        }
      }
    });

    const attributeMappings = {
      'data-title-key': 'data-title',
      'data-description-key': 'data-description',
      'data-alt-key': 'alt',
      'data-aria-label-key': 'aria-label',
      'data-placeholder-key': 'placeholder'
    };

    Object.entries(attributeMappings).forEach(([keyAttr, targetAttr]) => {
      document.querySelectorAll(`[${keyAttr}]`).forEach((element) => {
        const translationKey = element.getAttribute(keyAttr);
        const translatedValue = translations[selectedLang]?.[translationKey];

        if (translatedValue) {
          element.setAttribute(targetAttr, translatedValue);
        }
      });
    });

    document.querySelectorAll('[data-i18n-placeholder]').forEach((element) => {
      const key = element.getAttribute('data-i18n-placeholder');
      const translatedPlaceholder = translations[selectedLang]?.[key];

      if (translatedPlaceholder) {
        element.placeholder = translatedPlaceholder;
      }
    });

    document.querySelectorAll('.lang-btn').forEach((button) => {
      const isActive = button.getAttribute('data-lang') === selectedLang;
      button.classList.toggle('active', isActive);
      button.setAttribute('aria-pressed', isActive ? 'true' : 'false');
    });

    window.getTranslation = function (key) {
      const currentLang = document.body.getAttribute('data-lang') || defaultLang;
      return translations[currentLang]?.[key] || '';
    };
  }

  function initCarousel() {
    const carousel = document.querySelector('[data-carousel]');
    if (!carousel) return;

    const slides = Array.from(carousel.querySelectorAll('.carousel-slide'));
    const prevButton = carousel.querySelector('.carousel-button.prev');
    const nextButton = carousel.querySelector('.carousel-button.next');
    const indicators = Array.from(carousel.querySelectorAll('.carousel-indicator'));
    let activeIndex = slides.findIndex((slide) => slide.classList.contains('active'));
    if (activeIndex < 0) activeIndex = 0;

    const updateState = (index) => {
      activeIndex = (index + slides.length) % slides.length;
      slides.forEach((slide, slideIndex) => {
        const isActive = slideIndex === activeIndex;
        slide.classList.toggle('active', isActive);
        slide.setAttribute('aria-hidden', (!isActive).toString());
      });
      indicators.forEach((indicator, indicatorIndex) => {
        const isActive = indicatorIndex === activeIndex;
        indicator.classList.toggle('active', isActive);
        indicator.setAttribute('aria-selected', isActive ? 'true' : 'false');
      });
    };

    prevButton?.addEventListener('click', () => updateState(activeIndex - 1));
    nextButton?.addEventListener('click', () => updateState(activeIndex + 1));
    indicators.forEach((indicator, index) => {
      indicator.addEventListener('click', () => updateState(index));
    });
  }

  const savedLang = window.localStorage.getItem(storageKey);
  const initialLang = savedLang && translations[savedLang] ? savedLang : defaultLang;
  applyLanguage(initialLang);
  initCarousel();

  document.addEventListener('click', (event) => {
    const button = event.target.closest('.lang-btn');
    if (!button) return;

    const selectedLang = button.getAttribute('data-lang');
    if (!selectedLang) return;

    window.localStorage.setItem(storageKey, selectedLang);
    applyLanguage(selectedLang);
  });
})();
